### PR TITLE
Update Zcash and Dash text

### PR DESCRIPTION
**Pull request by SamsungGalaxyPlayer**
I updated the Zcash text to be more accurate, and I updated the Dash text to be more descriptive.

### CODE REVIEW

**Comment by Shifterovich** [comment]
Could you provide sources of that data?

**Comment by SamsungGalaxyPlayer** [comment]
[Information on Dash](https://www.dash.org/darksend/) (their website seems to be down at the moment, so you may need to fetch an [archived version](https://webcache.googleusercontent.com/search?q=cache:F70HpzJsEQIJ:https://www.dash.org/darksend/+&cd=1&hl=en&ct=clnk&gl=us)).

> PrivateSend is the feature that gives Dash users full privacy when they use it. It is an improved and extended version of the CoinJoin.

[Information on Zcash](https://z.cash/technology/index.html):

> Zcash also enables users to send public payments which work similarly to Bitcoin. With the support for both shielded and transparent addresses, users can choose to send Zcash privately or publicly. Zcash payments sent from a shielded address to a transparent address reveal the received balance, while payments from a transparent address to a shielded address protect the receiving value.

I disagree with many of the claims in these sources, but the facts as I have updated them are accurate.

**Comment by afighttilldeath** [comment]
I agree with SGP that Dash and Zcash's text is inaccurate. 

Zcash does not hide transactions automatically as most transactions are transparent, in fact, I'm not aware of an exchange that supports z-addresses (shielded addresses). The shielded addresses are used approximately 10% of time (I'm being generous).

Dash is not "privacy-centric" as most of their marketing is towards fast transactions as apparent through the original text where the writer talked about "instant transactions" and 'making transactions without waits' on a privacy-centric website.  In addition, Dash's privacy is hinged on the improved and extended version of CoinJoin which relies on a small percentage of users who have "Masternodes". One thousand Dash is required to have a Masternode and the current supply of Dash is 7.4 million. It is important to note that in the first 48 hours of Dash launching approx. two million Dash was mined so there is a good possibility a small percentage of people own Masternodes.

My recommendation for Dash:
Dash is an open-source, Bitcoin-based cryptocurrency that offers an improved version of CoinJoin called PrivateSend through the use of Masternodes.

Zcash Source:
https://z.cash/support/faq.html (Under "Are only a small fraction of Zcash users using shielded addresses?"
https://explorer.zcha.in/statistics/usage (this is referenced on FAQ in regards to transaction statistics)
https://www.reddit.com/r/zec/comments/5hyyc1/do_any_exchanges_give_shielded_addresses_for/

Dash Source:
https://www.dash.org/wp-content/uploads/2015/04/Dash-WhitepaperV1.pdf
https://dashpay.atlassian.net/wiki/display/OC/Dash+Instamine+Issue+Clarification

**Comment by Shifterovich** [comment]
> Dash is an open-source, Bitcoin-based cryptocurrency that offers an improved version of CoinJoin called PrivateSend through the use of Masternodes.

Explain what those buzzwords mean, though.

**Comment by hyc** [comment]
I think the main point is as I outlined it in issue #207 none of these others are private by default.

But even calling Dash "privacy-centric" is inaccurate as it's clear that the CoinJoin protocol it uses has zero privacy guarantees.

**Comment by Shifterovich** [comment]
We can easily remove Dash. It's just in the Worth Mentioning section.

**Comment by afighttilldeath** [comment]
@Shifterovich Sorry, I forgot this isn't a cryptocurrency website. lol, it's hard to explain without going too into it. I'd recommend removing Dash.

**Comment by Shifterovich** [comment]
I meant

> CoinJoin-based mixing system called PrivateSend

instead of

> improved version of CoinJoin called PrivateSend through the use of Masternodes

Anyway, I'm no cryptocurrency expert, but I haven't heard good things about Dash either.

**Comment by SamsungGalaxyPlayer** [comment]
@Shifterovich @afighttilldeath I also recommend its removal, though I imagine that should go in a different pull request. This request only intends to make the current wording more accurate.

**Comment by Shifterovich** [comment]
Done :P

**Comment by Shifterovich** [comment]
> Unlike Bitcoin, Zcash transactions optionally hide the sender

Doesn't sound very good. Maybe just point out that it *has the ability* to hide the sender.

**Comment by afighttilldeath** [comment]
:+1:

**Comment by hyc** [comment]
Not to nitpick, but I kinda prefer "may optionally" to "have the ability". Feel free to disregard this comment if everyone else is happy with the latter.

**Comment by Shifterovich** [comment]
OP changed one word and it doesn't fit very well into the context. I'd at least change "optionally" to "can optionally" or like you suggested "may optionally". And indeed, "have the ability" doesn't fit in very well either given the context. I wasn't being literal when I said "point out that it *has the ability* to hide the sender."

**Comment by daira** [comment]
"Unlike Bitcoin, Zcash transactions can optionally hide the sender, recipient, and value of transactions in z-addresses."

This is not accurate. Hiding of sender, recipient, and value of transactions in z-addresses is not optional. Use of shelled transactions (between z-addresses) is optional. I suggest the following correction:

"Unlike Bitcoin, Zcash supports shielded transactions, which hide the sender, recipient, and value."

**Pull request merged**
