### PR TITLE
Reference Mastodon

### PR DESCRIPTION
**Pull request by ilpianista**
### Description
Mastodon is a GNU Social-compatible microblogging server

### HTML Preview

http://htmlpreview.github.io/?https://github.com/ilpianista/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
I suggest making it the first recommendation, as it seems quite popular.

**Comment by vaygr** [comment]
I second this.

**Comment by Jbastardov** [comment]
There should be a line recommending Mastodon, an open-source self-managed instance-based microblogging social network. The network of federated Mastodon instances forms one part of the Fediverse, a federated network that includes servers running any social network software that uses OStatus.

**Comment by Gargron** [comment]
Mastodon is [quite popular](https://mastopeek.app-dist.eu/), more so than GNU social and diaspora* combined. But more importantly, it's not built on top of GNU social in any meaningful way (it used to use the same protocol that GNU social used, but never shared any codebase and no longer uses that protocol for about a year now).

**Pull request merged**
