### PR TITLE
Proposal to add ExpressVPN to the list of VPN providers

### PR DESCRIPTION
**Pull request by x7p**
Proposal to add ExpressVPN to the list of VPN providers with extra layers of privacy

### Description

moved sv.svg to /img/flags/4x3
added ExpressVPN.gif to /img/providers
added ExpressVPN to the alphabetical list

### HTML Preview

https://htmlpreview.github.io/?https://github.com/x7p/privacytools.io/blob/master/index.html

### Reasoning

Hi Privacytools.io!
Thanks for the great work you're doing informing people how to defend their privacy.
At ExpressVPN we are also working hard to let people uphold people's privacy.
We'd love to get listed for these reasons, please write us if you have any questions!

1) No logs
2) Bitcoin payments accepted
3) Not US or UK based (nor 14 Eyes)
4) No restrictions on protocols or data volume
5) OpenVPN config files available, apps all support OpenVPN
6) Only email and password required to create an account
7) Excellent Blog with plenty of privacy tips
8) Site reachable via onion site
9) Best security and privacy practices, including solid CA files, perfect forward secrecy, strong cyphers

### CODE REVIEW

**Comment by x7p** [comment]
Hi @Shifterovich! Curious to hear what you think about this proposal! For disclosure, I am affiliated with ExpressVPN.

**Comment by Shifterovich** [comment]
Adding a VPN provider is a major update. I'll look into ExpressVPN and ask in the subreddit.

**Comment by privacytoolsIO** [comment]
ExpressVPN meets our criteria, I don't see an issue at the moment. 

I just changed the Free Trial to "Yes" since you guys offer a 30 day money back guarantee.

**Comment by x7p** [comment]
Happy to hear! All the best!

**Comment by mmrabbani** [comment]
Is there a security point that ExpressVPN is excluded from the VPN list recently?

**Pull request merged**
