### PR TITLE
Add Ubuntu touch

### PR DESCRIPTION
**Pull request by mariogrip**
## Description

This adds Ubuntu touch which is created and maintained by the UBports
community. Continuing where canonical left

## Screenshots

image

### CODE REVIEW

**Comment by pahakalle** [comment]
If this is added there should be a mention on the relatively small amount of **officially** supported phones.

screenshot 2

**Comment by danarel** [comment]
Maybe it would be best as a "worth mentioning" for now?

**Comment by danarel** [comment]
#725

**Comment by BurungHantu1605** [comment]
thanks

**Pull request closed without merging**
