### PR TITLE
Move bitcoin

### PR DESCRIPTION
**Pull request by kewde**
bitcoin might not be the most private but you'll need it to buy other coins, makes sense to put it first.

### HTML Preview

https://htmlpreview.github.io/?https://github.com/kewde/privacytools.io/blob/bitcoin/index.html#cryptocurrency

### CODE REVIEW

**Comment by Shifterovich** [comment]
Bitcoin is not a private CC.

The reason it's still in the top 3 is because it *can* be private when used correctly and is often required to buy CCs like XMR anonymously. I'm fine with removing it completely if there's a good alternative.

Monero is (somewhat) private, BTC is not. BTC should not be the first recommendation as that's what most would go for and that's a bad idea.

**Comment by kewde** [comment]
I will add a fair warning to Bitcoin about the privacy issues that should deter people from using it for said purposes. Bitcoin does offer privacy improvements in comparison to traditional (digital) payments solutions. Many of the VPN providers listed on the website for example only accept Bitcoin (atleast as far as the cryptocurrencies go), it remains the THE currency of the internet. There isn't a lot of usability to the privacy coins listed, in practice many people use them to anonymize their bitcoins.

**Comment by Shifterovich** [comment]
That I'm fine with.

**Comment by Shifterovich** [comment]
Maybe add a `<b>Caution: </b>`?

**Comment by kewde** [comment]
Added cation :+1:

**Comment by Shifterovich** [comment]
I did not approve this PR. Do not merge PRs without approval of another Collaborator.

**Comment by kewde** [comment]
>That I'm fine with.
Sounded like approval to me, you can revert the commit and make changes if you feel so.

**Comment by Shifterovich** [comment]
> That

Meant what you were referring to. Not that Zcash is 100% anonymous.

**Comment by hyc** [comment]
That's a pretty flimsy justification for this change. There are multiple exchanges where you can buy Monero with fiat - Kraken.com. Bitfinex.com, X-pay.cc, anycoindirect.eu, etc.

Echoing @Shifterovich 's comment - BTC should not be the first recommendation.

**Comment by Shifterovich** [comment]
At the very least, Zcash should be *after* Monero.

**Comment by kewde** [comment]
@Shifterovich 
Feel free to back that statement with facts that prove that Zcash is technically inferior to Monero.

**Comment by Shifterovich** [comment]
Arguably, as many comment threads have shown. Monero transactions being private by default is a fact.

**Comment by kewde** [comment]
@Shifterovich 
Feel free to back that statement with facts that prove that Zcash is technically inferior to Monero.

I know _exactly_ how Monero (and more specifically RingCT) works. Using anonymization by default does not make it technically superior. A transaction using RingCT is less anonymous than a Zcash transaction.

**Comment by alvinjoelsantos** [comment]
@kewde care to elaborate how RingCT (with stealth addresses) is less anonymous than a Zcash transaction?

**Comment by kewde** [comment]
@alvinjoelsantos #207

**Comment by hyc** [comment]
Since this patch was merged without getting any other collaborators' agreement, and the justification listed here is invalid, this patch should be reverted.

>bitcoin might not be the most private but you'll need it to buy other coins, makes sense to put it first.

As already pointed out in https://github.com/privacytoolsIO/privacytools.io/pull/247#issuecomment-313070941 the justification has no merit.

The discussion in #256 is moot until an agreement is reached. Meanwhile, the state of the text prior to this commit *was* agreed on by multiple parties.

**Comment by Shifterovich** [comment]
@hyc 

I agree. Until someone proves Zcash is superior to Monero, I'll go with the wisdom of the crowd.

**Comment by kewde** [comment]
I never approved the switch of XMR with BTC in the first place.
I approved XMR being added however.

**Comment by Shifterovich** [comment]
Except you did #239

**Pull request merged**
