### PR TITLE
Added warning about Signal

### PR DESCRIPTION
**Pull request by sevengali**
### Description

I added a warning about Signal needing a mobile number to register. #432 

First commit about ghostbin isn't present in this branch (is #435)

### HTML Preview

http://htmlpreview.github.io/?https://github.com/sevengali/privacytools.io/blob/sevengali-signal/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
Thanks. I'd maybe change "mobile number" to "phone number". I think that's more common.

**Comment by zero77** [comment]
@sevengali 
Although, you have to use a phone number to register and for verification, you can use a disposable number.

I think this is important to mention as there are many free disposable number services or it is possible to create your own.

**Comment by Shifterovich** [comment]
Set up a PIN if using a disposable number https://infosec-handbook.eu/blog/signal-myths/#m2

**Comment by zero77** [comment]
@Shifterovich 
>Set up a PIN if using a disposable number

yes, good point this should be mentioned also.

**Comment by Shifterovich** [comment]
@kewde The disposable number thing isn't mentioned.

**Comment by kewde** [comment]
@Shifterovich cd8f1e8

**Pull request merged**
