### PR TITLE
Remove Non-Free Search Engines

### PR DESCRIPTION
**Pull request by gjhklfdsa**
**Description** Remove Non-free Search Engines
**Has this been discussed before?** Yes, many times. Most popular is probably #912 .
**But don't free software search engines provide low quality results?** I don't know who started spreading this, but non-free engines like [DuckDuckGo](https://www.wikipedia.org/wiki/DuckDuckGo) get their search engines from the same sources.
It is called a meta search engine:  https://www.wikipedia.org/wiki/Metasearch_engine
**What free software search engines are there?** Many, the ones listed on privacytools.io are [SearX](https://www.wikipedia.org/wiki/Searx), [JiveSearch](https://jivesearch.com/), [Yacy](https://www.wikipedia.org/wiki/YaCy), and [MetaGer](https://www.wikipedia.org/wiki/MetaGer).

### CODE REVIEW

**Comment by BurungHantu1605** [comment]
Full libre is not a requirement. Usability and good search results is what counts.

**Comment by Mikaela** [comment]
Do we have those requirements listed anywhere? I hope they also include not bubbling.

**Comment by gjhklfdsa** [comment]
@BurungHantu1605 @Mikaela Libre makes everything better.
More transparency, can lead to better privacy.

I wasn't stating it as a requirement, but closed software is not transparent.
Therefore, we have no way to verify.

Libre Software fixes these issues.

**Comment by gjhklfdsa** [comment]
Privacytools.io states in its contribution guidelines to only show the best software for privacy.

If free software improves privacy, then shouldn't it count as a method to rate providers/software?

@BurungHantu1605 @Mikaela @blacklight447-ptio @Shifterovich @JonahAragon @Vincevrp

**Comment by gjhklfdsa** [comment]
Privacytools.io states in its contribution guidelines to only show the best software for privacy.

If free software improves privacy, then shouldn't it count as a method to rate providers/software?

@BurungHantu1605 @Mikaela

**Comment by blacklight447-ptio** [comment]
Thing is, software and providers are different things, whether a provider uses free software is pointless as a requirement as you can never verify it anyway.

**Pull request closed without merging**
