### PR TITLE
💬 Discussion | Free Software Tag to Email Providers

### PR DESCRIPTION
**Pull request by ghbjklhv1**
**Feature**: Add is free software (back-end and/or front-end) column to email providers.
**Why**?: You cannot trust non-free software by nature, it is not transparent.
More info: https://tutanota.com/blog/posts/open-source-email/;
Systems: https://www.fsf.org/resources/webmail-systems
**Can you verify that these are using free software?**: For front-end code it is very easy thanks to projects like LibreJS. For back-end it is illegal to mislead consumers, if they are breaking this then you may have bigger issues on your hand.
**Previous discussions**: This PR is meant to help further the discussion in #1026 

Definitions:

    Free software:
    https://www.gnu.org/philosophy/free-sw.html

### CODE REVIEW

**Comment by blacklight447-ptio** [comment]
We generally dislike it when people open up pull requests when its issue/ discussion hasnt even concluded yet. #1026 first has to be resolved.

**Comment by ghbjklhv1** [comment]
@blacklight447-ptio Sorry pal, misunderstanding.

**Comment by ggg27** [comment]
> I don't see the problem with a closed source back end, as your unable to see what they run anyway.

Self-hostable email solutions are the exception, although I guess they could still sneak in code.

They key principle is that it would be illegal, as it would be lying to consumers.

@blacklight447-ptio 
[[replying to]](https://github.com/privacytoolsIO/privacytools.io/issues/1026#issuecomment-511328842)

**Comment by Mikaela** [comment]
@dngray What do you make of this?

**Pull request closed without merging**
