### PR TITLE
Add Section for Calendar and Contacts Sync

### PR DESCRIPTION
**Pull request by NeverDucky**
new file:   img/misc/email.png
	new file:   img/provider/etesync.png
	modified:   index.html
added calendar and contacts sync section

### Description
A potential section for calendar and contacts sync options. I'm curious as to what everyone thinks of the options.

### HTML Preview

*Replace [GITHUB_USERNAME] with your GitHub username and [BRANCH] with the branch name.*

http://htmlpreview.github.io/?https://github.com/neverducky/privacytools.io/blob/master/index.html#calendar_contacts

### CODE REVIEW

**Comment by Hillside502** [comment]
> EteSync is a secure, End-to-End encrypted and journaled personal information (e.g. contacts and calendar) cloud synchronization and backup for Android. It costs $14 per year to use, or you can host the server yourself for free.

"End-to-End" should be "end-to-end"

Apart from that --- right on the money!

**Comment by Shifterovich** [comment]
@Hillside502 Merge?

**Comment by NeverDucky** [comment]
> "End-to-End" should be "end-to-end"
Apart from that --- right on the money!

Haha I just copied it from their website; I fixed it though. I also added link to the section in the drop-down in the header.

**Comment by NeverDucky** [comment]
some discussion also going on [here](https://www.reddit.com/r/privacytoolsIO/comments/88bt1n/secure_service_for_syncing_contactcalendar/) by the way

**Comment by Hillside502** [comment]
@Shifterovich 
Yes, please!
Nice references to Nextcloud and, of course, the fairly unique EteSync.

**Comment by NeverDucky** [comment]
thank you ^_^

**Comment by tasn** [comment]
Hey,
Awesome work, thanks!

Just one comment, EteSync is also supported on [the desktop](https://github.com/etesync/etesync-dav/) and [the web](https://github.com/etesync/etesync-web/), so it should probably be updated.

Should I open a new ticket about it since this PR has already been merged?

**Comment by NeverDucky** [comment]
Oh I missed that it's also a web app. I'll open a PR to add that to the OS list. Though as far as "desktop" goes from what I can see that's not a native app but rather an implementation of the CalDAV and CardDAV protocol so I can add that to the description.

**Pull request merged**
