### PR TITLE
Revert "Switch Bitcoin and Monero"

### PR DESCRIPTION
**Pull request by kewde**
Reverts privacytoolsIO/privacytools.io#267

### CODE REVIEW

**Comment by Shifterovich** [comment]
Are you fucking kidding me?

Enough of this bullshit. PMing Burung to remove you as a collaborator.

**Comment by kewde** [comment]
Holy smokes, there is no need to start with foul language, the moment you are in disagreement. 
There is still no consensus with an active debate going on in #256.

**Comment by Shifterovich** [comment]
The majority decided and you're reverting commits because you don't agree.

**Comment by unknownids** [comment]
I personally think this is a grudge he holds going back to the animosity between Shadowcash and Monero. Theres no good reason.

**Pull request merged**
