### PR TITLE
put Muonium on self hosting and cloud storage services sections

### PR DESCRIPTION
**Pull request by Super-Baleine**
Hey!

### Description
I put [Muonium](http://github.com/muonium) as another alternative. Which is an actual encrypted cloud, opensource and so on 🐳 

### HTML Preview

http://htmlpreview.github.io/?https://github.com/Super-Baleine/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
Next time please disclose affiliation.

**Comment by Super-Baleine** [comment]
@Shifterovich what do you mean?

**Comment by Shifterovich** [comment]
That you work for muonium.

**Comment by Super-Baleine** [comment]
Oh yea, sorry, I didn't it was required. Why would you need it?

**Comment by kewde** [comment]
I haven't heard of this project before, I don't mind listing it in the worth mentioning as long as nobody has objections.

**Comment by Shifterovich** [comment]
Haven't heard of it either and don't think everything that's open-source is worth mentioning. I'll wait for @privacytoolsIO's review.

**Comment by privacytoolsIO** [comment]
Sorry guys, I'm very late to the party. I've posted it in our subreddit and added it to the website:

https://www.reddit.com/r/privacytoolsIO/comments/6rxzzc/muonium_encrypt_your_files_open_source_self/

https://privacytoolsio.github.io/privacytools.io/#mycloud

**Comment by Super-Baleine** [comment]
That's OK, thanks very much! 😄  👍

**Pull request merged**
