### PR TITLE
Switch Bitcoin and Monero

### PR DESCRIPTION
**Pull request by Shifterovich**
### Description

#247 #256 

### HTML Preview

http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/Shifterovich-switch-btc-xmr/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
Reverting an unapproved change.

**Comment by kewde** [comment]
The initial PR #239 wasn't approved either, what I reverted with move Bitcoin was an addition that I did not agree with.

**Comment by Shifterovich** [comment]
> kewde reviewed 15 days ago 
> :+1:

**Comment by kewde** [comment]
I did not agree with the switch of Bitcoin, that went under my radar, hence I reverted it.

**Comment by Shifterovich** [comment]
Except you're not the one who decides which CCs go on the website only because you develop Particl.

**Comment by kewde** [comment]
I don't decide indeed, I'm trying to achieve consensus and there is an active debate going on.

**Pull request merged**
