### PR TITLE
Reformulate Routers and add Linux Tools

### PR DESCRIPTION
**Pull request by hugoncosta**
## Description
Regarding #680 
Changed the name of routers to "Network Security" in order to be more encompassing.
Created a new section for Linux tools. Right now just has Gufw, but looking for suggestions on what to add besides it (sandboxing software, you name it).

## Screenshots
https://i.imgur.com/Sj9LjcB.png

### CODE REVIEW

**Comment by asddsaz** [comment]
[Gufw](https://en.wikipedia.org/wiki/Uncomplicated_Firewall) is Linux only. Although, it is a great piece of software and would highly recommend it.

**Comment by Mikaela** [comment]
I think gufw being a GUI for UFW should be mentioned as currently it seems to be presented as a standalone firewall.

I would recommend ufw directly whenever possible though, the syntax isn't very complicated and it ships with at least Ubuntu even if it's disabled by default.

**Comment by hugoncosta** [comment]
Was unsure about adding the reference, but makes sense, I'll add it

**Comment by Mikaela** [comment]
I think it only ships with Ubuntu, or at least not with Arch, Debian or Fedora.

**Comment by Shifterovich** [comment]
Isn't UFW based on iptables? I think there should be some cross-distribution iptables GUI tool.

**Comment by Mikaela** [comment]
Yes, UFW is an iptables frontend and does ip6tables simultaneously.

**Pull request closed without merging**
