### PR TITLE
Added Russia to "Key disclosure law" section

### PR DESCRIPTION
**Pull request by c0rdis**
### Description
 https://www.hrw.org/news/2016/07/12/russia-big-brother-law-harms-security-rights

### HTML Preview

http://htmlpreview.github.io/?https://github.com/c0rdis/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by Hillside502** [comment]
> "Internet and telecom companies will be required to disclose communications and metadata, as well as “all other information necessary,” to authorities, on request and without a court order."
https://www.hrw.org/news/2016/07/12/russia-big-brother-law-harms-security-rights

Insufficient to show that this includes "**key** disclosure".

The above HTML Preview doesn't show the changes --- only the hrw.org link.

Also:-
Key disclosure law - Wikipedia
https://en.wikipedia.org/wiki/Key_disclosure_law
has nothing for Russia.

**Comment by c0rdis** [comment]
Is this sufficient then? 
https://www.bloomberg.com/news/articles/2018-03-20/telegram-loses-bid-to-stop-russia-from-getting-encryption-keys

Updated preview link: 
http://htmlpreview.github.io/?https://github.com/c0rdis/privacytools.io/blob/patch-1/index.html

**Comment by Hillside502** [comment]
You need to preserve alphabetical order, by slotting in Russia between Norway and South Africa.

> "Putin signed laws in 2016 on fighting terrorism, which included a requirement for messaging services to provide the authorities with means to decrypt user correspondence."
https://www.bloomberg.com/news/articles/2018-03-20/telegram-loses-bid-to-stop-russia-from-getting-encryption-keys

seems to cover it nicely.  Suggest using this link instead.

**Comment by c0rdis** [comment]
Updated as suggested

**Comment by Hillside502** [comment]
Neither of the above HTML Preview links point to the latest commit.

**Comment by c0rdis** [comment]
Check again link from comment #3

**Comment by Hillside502** [comment]
Thanks for updating the link target.

**Comment by c0rdis** [comment]
Do you need anything else to merge the commit?

**Comment by Hillside502** [comment]
Over to @Shifterovich for a decision.

**Pull request merged**
