### PR TITLE
Add net neutrality widget

### PR DESCRIPTION
**Pull request by Shifterovich**
### Description

Feel free to suggest any changes.

# DON'T MERGE

### HTML Preview

http://theprivacyguide.org/ptio/index.html#ALWAYS_SHOW_BFTN_WIDGET (htmlpreview.github.io wouldn't work due to iframes, so I used a domain I own to host the preview)

### CODE REVIEW

**Comment by kewde** [comment]
You can easily revert this with the button above^

Looking at the JS code now

**Comment by Shifterovich** [comment]
Button above creates a PR. #264

**Comment by kewde** [comment]
It does set a cookie however..

**Comment by Shifterovich** [comment]
I managed to replace all the external resources, but didn't want to touch the JS code much as I'm not a JS dev and it's minified. Damn, the expiration is one year. Can you change that to 1 day?

**Pull request merged**
