### PR TITLE
Upgrade cards to v2 and add Dnote

### PR DESCRIPTION
**Pull request by sungwoncho**
## Description

Resolves: #1074

* Upgraded the `card.html` partials to `cardv2.html` in the Digital Notebook section.
* Added Dnote

### CODE REVIEW

**Comment by sungwoncho** [comment]
@Mikaela @ghbjklhv1 That is a fair point. To that end, I have also started a [discussion](https://www.reddit.com/r/privacytoolsIO/comments/ckw78q/suggestion_to_add_dnote_to_the_digital_notebook/) on the subreddit.

@ghbjklhv1  As you have pointed out, the website source code is not available. However one can easily see that the website is a set of simple static pages with no malicious trackers. Also, thanks for the catch. I have listed the source code in source_code.md in https://github.com/privacytoolsIO/privacytools.io/pull/1075/commits/d2cc81a41f4e9bc8ff48635185fda5caa8589d61.

**Comment by ghbjklhv1** [comment]
@sungwoncho It actually isn't static, as it uses JS.
But, I couldn't find any trackers. We should be good there.

Considering your the author, I would like to inform you of LibreJS:
https://www.wikipedia.org/wiki/GNU_LibreJS
Consider supporting the project by licensing your JS.

**Comment by sungwoncho** [comment]
@ghbjklhv You're correct. The website does run around 70 lines of JavaScript for dynamic styles. I will consider licensing it in the long run.

**Comment by JonahAragon** [comment]
privacytools.io is not an advertising platform for new products. We definitely can't merge this in until everything has been addressed at #1074.

**Comment by sungwoncho** [comment]
@JonahAragon I see. Sorry if I came across marketing-y. Could you please clarify:

* what specifically you would like to see addressed in #1074?
* what constitutes an advertisement and contribution? This wasn't too clear from the past contributions.

Thanks for maintaining this list.

**Pull request closed without merging**
