### PR TITLE
Replace now deprecated CyanogenMod with its continuation, LineageOS

### PR DESCRIPTION
**Pull request by walletdude**
Replaces CyanogenMod with LineageOS, which has just begun active development.  [Was received positively on Reddit](https://www.reddit.com/r/privacytoolsIO/comments/5pisfn/we_need_to_remove_cyanogenmod_from_mobile/)

### CODE REVIEW

**Comment by kewde** [comment]
#136

**Comment by jadensite** [comment]
@kewde As long as Cyanogenmod is on the site, we should let people know it has been forked.

**Comment by kewde** [comment]
@walletdude I agree nonetheless. The website is currently not being updated tho
@Shifterovich

**Comment by johnnagro** [comment]
:+1:

**Comment by walletdude** [comment]
@kewde what happened to @privacytoolsIO?  Can't he just add a cron pull job or git hook as I've seen being discussed?

**Comment by Shifterovich** [comment]
He's a very busy person.

**Comment by bashrc** [comment]
I also noticed that this should be changed

**Comment by kewde** [comment]
I approve this merge by the way, but I haven't tested it yet.

**Comment by potato20** [comment]
Any update on this?

**Comment by Shifterovich** [comment]
Resolve the conflicts and we'll merge.

**Comment by crypdick** [comment]
@walletdude if you give me access to your repo I'm happy to fix the conflict

**Comment by Shifterovich** [comment]
https://github.com/privacytoolsIO/privacytools.io/commit/5d01c4b9f4d6a64678c4d147ddb20118b9750eab

**Pull request closed without merging**
