### PR TITLE
Introduce flag-icon-css and display select country flags

### PR DESCRIPTION
**Pull request by mitchellcash**

### CODE REVIEW

**Comment by alexbooker** [comment]
I think this is a nice addition. 

:+1: for using SVG images but can you please put them in the `img` folder and remove the ones we don't reference? Also, can you please link the source of the flags that I can check the licence. 

Thanks :smile:

**Comment by mitchellcash** [comment]
I can do.

With removing the ones we don't reference, I left them all there in case there were other parts of the project that could use them. What do you think?

It's an MIT licence. I'm no expert but I think it means we are safe to use?

https://github.com/lipis/flag-icon-css/blob/master/LICENSE

**Comment by alexbooker** [comment]
> With removing the ones we don't reference, I left them all there in case there were other parts of the project that could use them. What do you think?

My concern is that there are **500** icons which require 6mb. We use just 14 :scream: 

... It's a bit too unwieldy (relatively speaking) in terms of **1,** deployment and **2,** managing the Git repository.

Adding new flags in the future shouldn't be too much bother.

**Comment by mitchellcash** [comment]
Okay, agreed. Let me fix this commit

**Comment by mitchellcash** [comment]
@alexbooker updated and squashed commit, can you please review?

**Comment by alexbooker** [comment]
More awesome work :fire:. 
Merged :smile:!

**Comment by mitchellcash** [comment]
Woo, thanks @alexbooker

**Comment by privacytoolsIO** [comment]
Good job, guys! Thanks

**Pull request closed without merging**
