### PR TITLE
Add RetroShare to "Encrypted Instant Messenger" Worth Mentioning

### PR DESCRIPTION
**Pull request by asddsaz**
Add RetroShare to "Encrypted Instant Messenger" worth mentioning list.

### CODE REVIEW

**Comment by Shifterovich** [comment]
Encrypted => encrypted
messging => messaging
I2p => I2P

I'd make these small changes myself but I'm not on a computer and my GH client doesn't allow that.

Also, can we have an https link?

**Comment by asddsaz** [comment]
@Shifterovich Fixed!

**Comment by Shifterovich** [comment]
Does their website support HTTPS though? If yes, then please update the link.

**Comment by Shifterovich** [comment]
We already link to Retroshare and a few other pages with HTTP only.

**Comment by Vincevrp** [comment]
> We already link to Retroshare and a few other pages with HTTP only.

Maybe we should reconsider that?

**Comment by Shifterovich** [comment]
Related thread: https://github.com/privacytoolsIO/privacytools.io/pull/401

**Pull request closed without merging**
