### PR TITLE
Update search-engines.html, Add cyber

### PR DESCRIPTION
**Pull request by serejandmyself**
Add cyber - A decentralized, web3, alternative to Google

#### Check List 

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Code repository of the project (if applicable): https://github.com/cybercongress/cyberd

Resolves: #1646

### CODE REVIEW

**Comment by LizMcIntyre** [comment]
DId Cyber answer the Questions to Ask all Privacy Services? I didn't see the answers if so.

[PTIO needs to decide if it wants to move forward with the Questions to Ask all Privacy Companies  project](https://forum.privacytools.io/t/approving-questions-to-ask-all-privacy-companies/2411). If so, it would be best to have new services answer the questions before being posted as recommended IMHO.

**Comment by serejandmyself** [comment]
> DId Cyber answer the Questions to Ask all Privacy Services? I didn't see the answers if so.
> 
> [PTIO needs to decide if it wants to move forward with the Questions to Ask all Privacy Companies project](https://forum.privacytools.io/t/approving-questions-to-ask-all-privacy-companies/2411). If so, it would be best to have new services answer the questions before being posted as recommended IMHO.

I must have missed them. My apologies if so. Maybe I can answer them now?

**Comment by Mikaela** [comment]
Sorry, I seem to have missed https://github.com/privacytoolsIO/privacytools.io/pull/1645, possibly, because you are going against the template and removing `Resolves: #1645` which you can find from [Closing issues via commit messages](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

**Comment by serejandmyself** [comment]
> I really dislike how you open a PR to advertise yourself without even respectfully disclosing that you are affiliated with the project. It's also our policy to first have an issue to discuss the issue before having a PR (although I think I wouldn't mind having both an issue and a PR to close it roughly at the same time).
> 
> I am also interested in the answers to the questions linked above.

Hey! By no means I am hiding the fact I am affiliated with the project. Of course I am. It's all over my profile. I wasn't aware of the fact that this is against the rules. Seems like a lot of politics to open a PR =) 

TBH, I still do not understand the PTIO thing above. I guess I will just close the PR for now and add info to the issue (although after reading the contributing guidelines, I did not see the inability to open a PR along with an issue. In fact it seems more logical to me). 

In any case, let's follow the existing set of rules and move the discussion to #1646

**Comment by Mikaela** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/1646#issuecomment-573398419

**Comment by serejandmyself** [comment]
> Who owns the company/organization? What percentage does each owner hold? (December 31 of prior year and current date)

There is no company/organisation at all. We do not believe in legislation. We do not believe in law by default. There is a DAO (a decentralized autonomous organisation on the blockchain, run with the help of smart contracts) that is called cyber~ Congress. For launching the protocol and for financing its first 3 years of work (roughly 1.2 million USD - disclosed in our FAQ's), it receives up to 10% of THC tokens, which it will stake (on the same "rules" as the other participants) and receive an equal amount of CYB tokens. 
The funding of the protocol is the following: the first round of donations goes to cyber congress, which will be staked for a validator, and the rewards will be used by cyber~Congress to fund proposals from team members (for example one of those is the ecosystem fund to help evolve the protocol). 
The main round of donations will be governed by the community itself, which is going to be held in ETH, thorough governance proposals. 
There was also an initial donation round, in which 10 people participated (although it was open to the broad public), for which they will receive up to 10% of CYB tokens too. 
All this info is public on our GitHub, in our White paper and our economic docs. By our calculations, the congress and affiliated people will have up to 14% of the tokens. We understand that this is quite a lot. And our goal is to wash down to 2% in the next 15 - 20 years (of course I am referring to the tokens of the congress. We cannot washdown the tokens of non-congress members, even if they are affiliated).
In any case, the whole protocol is community-governed. It should also be noted that 10% were gifted to the following communities: 8% to over 1 million ETH addresses, 1% to ATOM addresses and 1% to Urbit addresses. 

> Have you changed how information is processed and shared in the last year?

No, we use GitHub for ALL of our information. It is our goal to open-source ALL the information that we produce. 

The blog, website, etc are all run from our GitHub account. There is, of course, Twitter, reddit, etc which aren't. But they are all public. 

>Do you share data -- even "fuzzed" or "anonymized" data -- with any of the owners/shareholders or any other company or organization server?

We do not collect any data. The blockchain is, of course, open to the public. All transactions are hashed of course.
 
> Please share a diagram showing how information flows when a user interacts with your service.

I believe the best place for this is here: https://ipfs.io/ipfs/QmceNpj6HfS81PcCaQXrFMQf7LR5FTLkdG9sbSRNy3UXoZ
Please see pages: 2,3,4,8 and 9 for such diagrams 

> Which components of your service are not open source? Where can we find the code for the open source components?

They are ALL open-source. Including our plans, writings, code, etc, etc, etc
Our GitHub account: https://github.com/cybercongress
 
> Have you had any independent audits in the last three years? Please share the dates of those audits and audit reports.

No. We have not done any audits of the code yet. It is open to the public. 

> If you require sign-up or account creation, do consumers have easy access to tools to delete their data? Can they delete everything on the servers or just the local cache?

There is no sign-up as such. An identity is a pair of keys created on the blockchain. 

> Is there a way for consumers to view any information you have collected about them?

We do not collect consumer information. Any user can open the explorer to see available info about any transaction, account, etc 

> What is your business model? How do you fund operations and make money?

As of now, the project is self-funded. In the future, it is planned to fund from the staking rewards of ATOMs 

> Do you offer a transparency report? Warrant canary?|

No. The project is open-sourced. 100%

> How is data secured (in transit and at rest)?

It is secured by the blockchain. The more nodes that will be connected to the protocol, the better security it will have. The more tokens will be staked, the more secure the chain will become. 

> Who has access to customer data?

Anyone with access to the blockchain / explorer. But there is no customer data as such to see there. 

> What 3rd parties have access to customer data?

None

> What processes do you have in place if there is unauthorized access to data?

This means the blockchain has been hacked. As of today, this has never happened. If such a case arises, it will mean a lot of changes in cryptography generally. But in terms of a solution, I believe a fork is possible. Bu this will be decided by a governance protocol. 

> What customer data is collected, how often, and in what level of identification?

None, in terms of "data collection". BUT,
Each cyberlink contains hashes of what was linked, when, with what weight and by which node. 
When Cyb, the browser is out and stable, I assume that some people would sell their own data, via APIs. We cannot control this. The browser in our case will be a personal application on top of the protocol that the user and only the user controls. 

>  Will changes to your Terms & Conditions and privacy policies be communicated to end users at least 30 days in advance of any changes? How will these changes be communicated?

We do not have terms & conditions as of now. The license is: don't believe, don't fear, don't ask

> Do you commit to notifying consumers at least 30 days in advance if you plan to sell your service or take on new investors/owners? How will this be communicated?

After the donations and governance contracts, the protocol is solely community governed. It will be up to the protocol to decide on such things, how to communicate this, etc. 

All the information provided is true and correct to today. Once again, the idea of the protocol is to be community governed via a set of smart contracts and economy. The governing protocol may change pretty much anything that is parametrized (which is almost everything...) though voting mechanisms and A/B testing

**Comment by serejandmyself** [comment]
Hey guys, just wanna see if there is any update on the PR?

**Comment by serejandmyself** [comment]
@Mikaela Just wondering if you had the chance to take a look in the answers #1646 ?
Am I missing anything else?

**Comment by Mikaela** [comment]
I am currently avoiding making editorional decisions as the first one at least as I don't view myself as the correct person to do that.

@privacytoolsIO/editorial ping?

**Comment by serejandmyself** [comment]
Sure, let me know. I believe I answered all of the questions that were there. However, will be happy to add more info if needed

**Pull request closed without merging**
