### PR TITLE
Update Edward Snowden quotes from Permanent Record

### PR DESCRIPTION
**Pull request by sgraaf**
## Description

Resolves: #none 

#### Check List 

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-1654--privacytools-io.netlify.com/

### CODE REVIEW

**Comment by sgraaf** [comment]
> 
> 
> Thank you for this PR, I checked that the quotes are correct, but the only thing I am not certain of is linking to Amazon.
> 
> As I didn't find any official website for the book, what would you think about linking to Wikipedia (or would it give spoilers) or Goodreads (I am not sure if this one is justifiable) instead?
> 
>     * https://en.wikipedia.org/wiki/Permanent_Record_(autobiography)
> 
>     * https://www.goodreads.com/book/show/46223297-permanent-record
> 
> 
> If everyone else is fine with linking to Amazon, could the link point at least to smile.amazon.com so Amazon will donate some to charities [including Tor (see question 26)](https://donate.torproject.org/donor-faq)?

I was unsure about linking to Amazon myself. Linking to Goodreads seems like a perfectly fine substitute.

**Comment by danarel** [comment]
> I was unsure about linking to Amazon myself. Linking to Goodreads seems like a perfectly fine substitute.

Amazon own's Goodreads.

I would recommend linking directly to the publisher and letting the user decide where to buy:

https://us.macmillan.com/books/9781250237231

**Comment by Mikaela** [comment]
> Although I’m inclined to recommend just downloading a copy online due to this:

I fear that would get copyright people after us, while it would be interesting how much information there can be about that.

Unless you just said (note: Edward Snowden doesn't receive money from the book)?

**Comment by dngray** [comment]
We probably can't link to a pirated copy of the book no. But we certainly shouldn't link to a shopfront of any kind given that all money is being confiscated.

**Comment by nitrohorse** [comment]
@sgraaf, would you be able to update the link to Wikipedia? Then we could merge I think.

**Comment by danarel** [comment]
Is there a reason why we are choosing Wikipedia over the publishers site?

**Comment by nitrohorse** [comment]
I’d think Wikipedia could be a bit more informative for users due to it containing info on the civil lawsuit, specifically that the US government “aims to capture the proceeds Snowden would be earning from [the book].”

**Comment by danarel** [comment]
Fair enough

**Comment by sgraaf** [comment]
> 
> 
> @sgraaf, would you be able to update the link to Wikipedia? Then we could merge I think.

Yes. Will do so tomorrow.

**Comment by sgraaf** [comment]
> 
> 
> @sgraaf, would you be able to update the link to Wikipedia? Then we could merge I think.

Done.

**Pull request merged**
