### PR TITLE
Remove national flags from the language select.

### PR DESCRIPTION
**Pull request by troutperch**
## Description

Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/185

### CODE REVIEW

**Comment by JonahAragon** [comment]
It’s live at https://deploy-preview-824--privacytools-io.netlify.com/ btw. 

Kind of broken on mobile:

29D92029-155E-4087-BD43-C4D7D0D7CC57

**Comment by Shifterovich** [comment]
@JonahAragon you set up PR previews? That's cool, I wanted to write a bot for that. Can you easily make netlify comment with a link to the preview when the PR is submitted?

**Comment by JonahAragon** [comment]
@Shifterovich if you click Details on the deploy/netlify check it will open:

image

But, I can set it up to do comments as well I'm pretty sure. I'll investigate that.

**Comment by BurungHantu1605** [comment]
I'll close this one here since it's not working right and the other version submitted is live and working.

**Comment by JonahAragon** [comment]
...

image

But whatever @BurungHantu1605 :P

**Comment by BurungHantu1605** [comment]
Whatever :P haha. Now we have conflicting files

**Pull request closed without merging**
