### PR TITLE
Let AMO automatically detect the appropriate language

### PR DESCRIPTION
**Pull request by IDKwhattoputhere**
Let AMO decide which localization fits best. Similar to https://github.com/nylira/prism-break/issues/1441.

### CODE REVIEW

**Comment by alexbooker** [comment]
Hi there, @IDKwhattoputhere :wave: . Thanks for your contribution. I checked that all the links still work and that the text hasn't been altered. Everything looks good.

I noticed you had an empty commit so I `cherry-picked` just the one with actual changes.

**Comment by IDKwhattoputhere** [comment]
Sounds great! I made that empty commit after editing the original file in Notepad++ a second time to make sure I catched all the links and didn't make any mistakes (perfectionism and such). Didn't know GitHub accepts empty commits. ¯\\\_(ツ)\_/¯

**Comment by privacytoolsIO** [comment]
Good idea! It's live: https://www.privacytools.io/

**Comment by IDKwhattoputhere** [comment]
Thanks! Keep up the great work!

**Pull request closed without merging**
