### PR TITLE
Removed extension that is no longer available

### PR DESCRIPTION
**Pull request by vRobM**
"Block Cloudflare MiTM Attack - Firefox add-on to detect and block corporate MITM attack. "

### CODE REVIEW

**Comment by Hillside502** [comment]
https://github.com/nym-zone/block_cloudflare_mitm_fx/issues/19

**Comment by kewde** [comment]
I think we'll have to remove this one..
If there's are no maintainers and only bug report with the extension attached as an addon, it is pretty much dead to me.

**Comment by kewde** [comment]
@shifterovich

**Comment by Shifterovich** [comment]
> If there's are no maintainers

If it's a simple script there might be no need to maintain it.

And what's the issue? FF removed some privacy addons from their addon website? Can't users install them locally from source/zip like on Chrome?

**Comment by Shifterovich** [comment]
https://trac.torproject.org/projects/tor/attachment/ticket/24351/block_cloudflare_mitm_attack-1.0.14.1-an%2Bfx.xpi

Email I received:

> I was the "developer" of this add-on.
> 
> The reason why there is no one to answer on Github is
> "nullius", the AMO maintainer who control my add-on[1]
> didn't answer to my emails since last year. I believe he's
> gone MIA, and it seems his email account is hacked.
> 
> We(me and nullius) failed to communicate with Mozilla idiots
> therefore the add-on remains hidden(or deleted, I have no idea
> because my AMO account level was "developer". I deleted AMO
> account after I noticed the add-on was hidden)

Alternative: https://addons.mozilla.org/en-US/firefox/addon/tprb/

**Comment by Shifterovich** [comment]
Anyway the xpi file still exists and users can install it even without AMO. Maybe just change the link?

**Comment by Shifterovich** [comment]
Wrong link, alternative: https://addons.mozilla.org/en-US/firefox/addon/bcma/

**Comment by vRobM** [comment]
CF is not an Attack. It's a contractual service. Stop the FUD.

++ Rob

About me <https://remote.com/r>

**Comment by n8v8R** [comment]
@vRobM The TLS certificate for remote.con is a typical CF SNI certificate and covering

1. DNS Name: ssl379641.cloudflaressl.com
2. DNS Name: *.algartoldo.com
3. DNS Name: *.blackmoonparanormalresearch.com
4. DNS Name: *.glasscityhog3753.com
5. DNS Name: *.go123.ph
6. DNS Name: *.hurricosmo.com
7. DNS Name: *.iloveecigs.com
8. DNS Name: *.lumbininepal-ca.org
9. DNS Name: *.philosophyofglass.com
10. DNS Name: *.physmodo.com
11. DNS Name: *.pinbadgememories.com
12. DNS Name: *.poliplex.net
13. DNS Name: *.remote.com
14. DNS Name: *.sahaltravel.com
15. DNS Name: *.solidaluminiumcane.co.uk
16. DNS Name: *.stoutbordeaux.com
17. DNS Name: *.texasstarwindows.com
18. DNS Name: *.thedaviesmusicacademy.com
19. DNS Name: algartoldo.com
20. DNS Name: blackmoonparanormalresearch.com
21. DNS Name: glasscityhog3753.com
22. DNS Name: go123.ph
23. DNS Name: hurricosmo.com
24. DNS Name: iloveecigs.com
25. DNS Name: lumbininepal-ca.org
26. DNS Name: philosophyofglass.com
27. DNS Name: physmodo.com
28. DNS Name: pinbadgememories.com
29. DNS Name: poliplex.net
30. DNS Name: remote.com
31. DNS Name: sahaltravel.com
32. DNS Name: solidaluminiumcane.co.uk
33. DNS Name: stoutbordeaux.com
34. DNS Name: texasstarwindows.com
35. DNS Name: thedaviesmusicacademy.com

The TLS traffic apparently terminating at CF's edge and thus accessible/legible (MitM) to CF. 

How is that for trusting?

Concur it is a business model (contractual service) but certainly not inspiring trust in the uninterrupted TLS chain with any such domain and thus there is nothing wrong with creating user awareness. 

---
Besides the WE is back online https://addons.mozilla.org/en-US/firefox/addon/bcma/

**Pull request closed without merging**
