### PR TITLE
Replace Trisquel with Fedora

### PR DESCRIPTION
**Pull request by JonahAragon**
Replaces Trisquel with Fedora as a top-3 choice, moves Trisquel to Worth Mentioning. This makes a lot more sense to me as a general recommendation IMO, when I was going through the changes for #1148 I didn't really understand why Trisquel was recommended in the first place.

I would also be open to recommending elementaryOS instead of Trisquel or Fedora despite the comments against it at #1130, if we'd prefer. But Fedora is also fine. I do think it's important to have an easier recommendation, Qubes (and arguably even Debian) is somewhat extreme.

Resolves: #1130; Resolves: #449

### CODE REVIEW

**Comment by nitrohorse** [comment]
I have a soft-spot for elementary since it was the first Linux distro that seemed to get the UI/UX just right for me. It was also much easier to recommend to friends/family over using Windows in regards to its usability. I don't have experience with Fedora but it also sounds like a solid recommendation. I'm just wondering if elementary would bring a healthy balance to our OS recommendations that also keeps new users to Linux in mind?

**Comment by gjhklfdsa1** [comment]
> elementary
@nitrohorse My issue with ElementaryOS is that they seem to be "convenience first, security second".
You can set up Pantheon on Debian (`[pantheon-debian](https://gitlab.com/pantheon-debian/pantheon-debian/wikis/home)`) but it has some issues:
https://gitlab.com/pantheon-debian/pantheon-debian/issues/26

Plus, the NX Software Center works basically everywhere:
https://github.com/Nitrux/nx-software-center

**Comment by JonahAragon** [comment]
> Trisquel is a popular OS recommended by privacy experts worldwide for its ease-of-use and free/libre components and support.

Both of which are not privacy-centric features.

---

> Yum is basically only used in Fedora and Redhat. I do not understand how this benefits users in any way not provided by APT or GUIX.

Supporting a monoculture in the package manager space seems like not the best idea. Fedora, CentOS, and RHEL are **huge** distros too, so saying its "only" used in those distros understates its popularity.

---

> Fedora is for profit

As I stated at https://github.com/privacytoolsIO/privacytools.io/issues/1130#issuecomment-520963685, Fedora is a community led project:

> Saying Fedora is owned by Red Hat would be like saying Debian is owned by Canonical

RHEL "owning" Fedora seems to be a common misinterpretation, but it's pretty obviously debunked.

---

> From a UI standpoint

Fedora runs GNOME. That's basically the easiest-to-understand desktop environment around. The only better DE from a purely UI perspective (IMO) is Elementary's. Trisquel looks straight out of 2012.

---

> I have a soft-spot for elementary since it was the first Linux distro that seemed to get the UI/UX just right for me. 

Agree, which is why I'd also be fine listing it, it is fantastic software. But from especially a security perspective Fedora seems to come out on top. Also we currently recommend Debian (and Trisquel for the time being), both of which are apt-based, so I think throwing another package manager in the mix is a good thing. Elementary is basically Ubuntu with another DE and custom apps, but the underlying software is the same.

---

The main things I like about Fedora are 1) it isn't Debian-based like our other recommendations, and 2) it has a very security-focused approach. As @blacklight447-ptio stated at https://github.com/privacytoolsIO/privacytools.io/issues/1130#issuecomment-520738986: 

> also, fedora is out of the box a lot more secure then debian. it has Selinux out of the box, it applies a ton of hardening patches aswell, it also uses wayland, which is all listed above.

**Comment by nitrohorse** [comment]
> from especially a security perspective Fedora seems to come out on top. Also we currently recommend Debian (and Trisquel for the time being), both of which are apt-based, so I think throwing another package manager in the mix is a good thing.

Ah, that's a good point I didn't think about. Makes sense! :+1:

**Comment by ggg27** [comment]
Just to be clear:

> The project was founded in 2003 as a result of a merger between the Red Hat Linux (RHL) and Fedora Linux projects. Red Hat employees make up only 35% of project contributors, and most of the over 2,000 contributors are unaffiliated members of the community.

________________

If you want a diffrent package mangaer may I recommend GUIX of Pacman?

**Pull request merged**
