### PR TITLE
Search engines: add Ecosia

### PR DESCRIPTION
**Pull request by Mikaela**
Resolves: #682

The issue above is in disagreement and requires attention on whether Tor
blocking is a reason to not merge this.

### CODE REVIEW

**Comment by nitrohorse** [comment]
Hmm so...
1) I really do like that they use their profits to plant trees,
2) that their privacy policy is short and reasonably respectful for users, and
3) that they honor the Do Not Track browser setting.

On the other hand, in my perspective...

1) it's unfortunate Ecosia doesn't proxy requests to Bing like Startpage does to Google. Requests to Bing.com and Bing.net are made when searching. (Note: I also noticed (at least) on their [iOS app](https://apps.apple.com/us/app/ecosia/id670881887) that additional requests are made to "a-0001.a-afdentry.net.trafficmanager.net" (a [CNAME for Bing.com](https://urlscan.io/domain/www.bing.com)) and "dual-a-0001.a-msedge.net")
2) I wish they provided an option [in their settings page](https://www.ecosia.org/settings) (like [Startpage](https://eu.startpage.com/search/settings) and [DuckDuckGo](https://duckduckgo.com/settings) do) for using POST or GET when making the search request. Both have their privacy trade-offs but Ecosia locks users into using GET.
3) Looking at Ecosia's statement here:

> "...we forward the following information to our partner, Bing: IP address, user agent string, search term, and some settings like your country and language setting." -- https://info.ecosia.org/privacy

Besides Ecosia's tree-planting mission, I wonder if there is a significant privacy-gain over directly using Bing. Since requests from Ecosia are "forwarded" to Bing, is it correct to assume my queries on Bing's side fall under [Microsoft's user-hostile privacy policy](https://privacy.microsoft.com/en-us/privacystatement)?

**Comment by Mikaela** [comment]
@nitrohorse so shall we close the Ecosia case *permanently*? "We love trees and planting them, but due to some concerns we won't be able to list it" ?

**Comment by nitrohorse** [comment]
@Mikaela yeah, I think we should.

**Comment by Mikaela** [comment]
Case closed, see comments of #682 and comments starting from https://github.com/privacytoolsIO/privacytools.io/pull/1036#pullrequestreview-263991424.

**Comment by bcye** [comment]
Hey @nitrohorse and @Mikaela ,

I just tried using Ecosia on my computer via the TOR browser and it just worked fine. It is still not proxying search requests but sending them to bing, but I think this should not be a deal-breaker and that Ecosia should be at least added as a "Worth Mentioning".

CleanShot 2020-04-30 at 19 52 40

**Comment by nitrohorse** [comment]
Hey @bcye, thanks for reaching out. I don't think my position has changed. Ecosia forwards requests to Bing which logs queries. And then "after 7 days [Ecosia] remove[s] all personal information (like the IP address) from [stored] search data." They take steps toward privacy but it's not as _high_ a priority like other search engines.

From my understanding, this is also unfortuanely the case for other environment-forward search engines that forward requests with personal information to Bing/Google such as [Ekoru](https://www.ekoru.org), [Lilo](https://search.lilo.org/), [OceanHero](https://oceanhero.today/), [YouCare](https://youcare.world), [Givero](https://www.givero.com/), and [Gexsi](https://gexsi.com/en).

**Pull request closed without merging**
