### PR TITLE
Add Minds to Decentralized Social Networks

### PR DESCRIPTION
**Pull request by asddsaz**
**Description**: Add Minds to Decentralized Social Networks "Worth Mentioning" section.
**Minds URL**: https://www.minds.com/
**Wikipedia**: https://www.wikipedia.org/wiki/Minds
**Doesn't Minds support hate speech**? Although, Minds doesn't censor content it does enable users to flag content that may be found offensive like nsfw. You may then opt-out/filter these.

### CODE REVIEW

**Comment by Shifterovich** [comment]
How exactly is it decentralized?

**Comment by hugoncosta** [comment]
I believe the "decentralized" part they refer to is the use of an ethereum token for payments. Nonetheless, this looks like a STEEM copy to me, I'm unsure if it should be featured.

**Comment by asddsaz** [comment]
> How exactly is it decentralized?

If I understand correctly they utilize a decentralized video content storage and have a self-host option (I haven't used it). They also have a decentralized reward system.

> I believe the "decentralized" part they refer to is the use of an ethereum token for payments. Nonetheless, this looks like a STEEM copy to me, I'm unsure if it should be featured.

STEEM is more of a blogging platform, I know this is a privacy community but have you ever used Facebook? It is very similar to that.

**Comment by gjhklfdsa** [comment]
@danarel They have a user-led censorship system. You can feel free to mark posts as NSFW.

**Comment by Shifterovich** [comment]
> Most Free Software social networks appear to get a lot of attention from censored groups like Neo-Nazis.

This will always happen, since they're the most censored group on most social media. I think Steemit is a bit better though? It's very good tech-wise and also community-wise afaik.

**Pull request closed without merging**
