### PR TITLE
Updated Mullvad VPN details with Play Store and App Store Links

### PR DESCRIPTION
**Pull request by xelarate86**
## Description
Per the [most recent activity](https://github.com/privacytoolsIO/privacytools.io/pull/1528#issuecomment-612105347) on the old PR #1528 I have reconfigured this request to make the required changes.

Given that Mullvad now has published Apps on both main app stores for Android and iOS, I have included links and corrected the incorrect documentation that mobile clients were still in the works.

Resolves: #1528 which was erroneously closed. (By me, oops).
#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: 
[Netlify Preview here](https://eager-colden-4cbe67.netlify.com/providers/vpn/)

* Code repository of the project (if applicable):
N/A

### CODE REVIEW

**Comment by xelarate86** [comment]
@Mikaela @danarel @JonahAragon Pinging you to this, updating #1528. Apologies for the poor practive in opening a new PR.

**Comment by danarel** [comment]
Do we want to link to the clients since we don’t for the other providers?

**Comment by JonahAragon** [comment]
@danarel no, not for consistency...... although I’d probably actually prefer adding links to the other two instead of removing these. Makes sense to list them IMO.

**Comment by xelarate86** [comment]
> Do we want to link to the clients since we don’t for the other providers?
@danarel I can change this quickly if you'd like - shall I?

**Comment by danarel** [comment]
> Uhhh reviewing on my phone, but LGTM

For Proton and IVPN we only mention they have mobile clients.  

I think we should either add them, or remove the links in the Mullvad description.

**Comment by xelarate86** [comment]
> > Uhhh reviewing on my phone, but LGTM
> 
> For Proton and IVPN we only mention they have mobile clients.
> 
> I think we should either add them, or remove the links in the Mullvad description.

I will add them and update this pull request @JonahAragon

**Comment by danarel** [comment]
> @danarel no, not for consistency...... although I’d probably actually prefer adding links to the other two instead of removing these. Makes sense to list them IMO. 

Agreed. I rather add links then remove them.

**Comment by xelarate86** [comment]
@danarel @JonahAragon Updated the PR with the IVPN and ProtonVPN links.
[A preview can be found at that same netlify link](https://eager-colden-4cbe67.netlify.com/providers/vpn/)

**Pull request merged**
