### PR TITLE
Add Movim to Decentralized Social Networks

### PR DESCRIPTION
**Pull request by asddsaz**
**Description**: Add Movim to Decentralized Social Networks "Worth Mentioning".
**Movim URL**: https://movim.eu/

### CODE REVIEW

**Comment by hugoncosta** [comment]
Looks like an interesting project, based on xmpp, nice addition to the list.

**Comment by zexi3453** [comment]
- https://github.com/movim/movim/issues/63 - Has no end-to-end encryption (OMEMO) support

**Comment by JonahAragon** [comment]
Has this been discussed at all before this PR?

**Comment by Mikaela** [comment]
> Has this been discussed at all before this PR?

Yes, kind of in form of https://github.com/privacytoolsIO/privacytools.io/issues/141 & https://github.com/privacytoolsIO/privacytools.io/issues/60 (even if I would recommend using Conversations and Gajim or Dino instead due to zexi3453's https://github.com/movim/movim/issues/63 (which seems to me to be happening especially after I started subscribing the issue last night)) and it's also mentioned in https://github.com/privacytoolsIO/privacytools.io/pull/562#issuecomment-459296479.

**Comment by BurungHantu1605** [comment]
added

**Pull request closed without merging**
