### PR TITLE
For Issue #381 Update VPN Price

### PR DESCRIPTION
**Pull request by Eduardo06sp**
### Description

Issue #381 
IVPN price changed to $100

### HTML Preview

*Replace [GITHUB_USERNAME] with your GitHub username and [BRANCH] with the branch name.*

http://htmlpreview.github.io/?https://github.com/Eduardo06sp/privacytools.io/blob/patch-1/index.html

### CODE REVIEW

**Comment by yassinei** [comment]
Thank you

**Comment by Eduardo06sp** [comment]
No problem! Baby steps first!

**Comment by kewde** [comment]
The data values for the VPNs are wrong, they should correspond with the actual values such that the sorting works properly. This is not your fault, but your PR made me took notice to it.
There is also a sporadic usage of EUR & USD which complicates the matter. The USD/EUR conversion rate fluctuates so it won't be accurate at every moment but w/e.

**Comment by kewde** [comment]
I don't think anything critical has changed, so I'll merge this over the weekend.

**Pull request merged**
