### PR TITLE
VPN ownership several Chinese companies

### PR DESCRIPTION
**Pull request by dngray**
https://deploy-preview-1805--privacytools-io.netlify.com/providers/vpn/#info

### CODE REVIEW

**Comment by dngray** [comment]
Should we do something to signify that is a video? We could embed the video too, with an invidious instance ie https://invidio.us/embed/WVDQEoe6ZWY?local=true I feel it should be more prominent rather than mixed up with the related links.

What do you think @nitrohorse?

**Comment by nitrohorse** [comment]
> Should we do something to signify that is a video? We could embed the video too, with an invidious instance ie [invidio.us/embed/WVDQEoe6ZWY?local=true](https://invidio.us/embed/WVDQEoe6ZWY?local=true) I feel it should be more prominent rather than mixed up with the related links.
> 
> What do you think @nitrohorse?

Hmm, that could be a good idea for visibility. Something like this?

embed-vpn

**Comment by dngray** [comment]
@nitrohorse yeah i think that looks rather good, and fits in with our page style.

**Comment by dngray** [comment]
@JonahAragon mentioned that it would be best to just host an image thumbnail with a play icon in the middle of it that people could click to open Invidious in a new tab.

He's said he will take a look at this tomorrow.

**Comment by dngray** [comment]
I think some changes need to be made to allow the use of jpg images. Ie if we wanted to use [this](https://i.ytimg.com/vi/WVDQEoe6ZWY/maxresdefault.jpg) as the image thumbnail.

I was thinking maybe something like:

```html
<li>
  <img src="./assets/img/jpg/3rd-party/this-video-is-sponsored-by.jpg">
  <a href="https://youtube.com/watch?v=WVDQEoe6ZWY">This Video Is Sponsored By ███ VPN</a>
</li>
```

Obviously image would need resizing though.

**Comment by nitrohorse** [comment]
Closing in favor of https://github.com/privacytoolsIO/privacytools.io/pull/1891!

**Pull request closed without merging**
