### PR TITLE
Reworked layout

### PR DESCRIPTION
**Pull request by Shifterovich**
Added FA icons, removed unnecessary sections

(@c0rdis #704)

### CODE REVIEW

**Comment by c0rdis** [comment]
"Share" with a dropdown and "Twitter", as both of them are immediately available when following "Participate", but imho looks much cleaner. Also, removed duplicates from "Software" section (which are already present in "Provider"), such as "DNS", "Social networks" and "Search engines"

**Comment by c0rdis** [comment]
Planning to also change a bit to more clearly reflect current structure, possibly copying "Most important" section from privacytools.ru. Hopefully tomorrow / next week, so will be a separate PR.

**Comment by Vincevrp** [comment]
Could you add some screenshots?

**Comment by c0rdis** [comment]
participate
os
software
browser
provider
header

**Comment by Vincevrp** [comment]
Looks good to me. If you're finished you can remove the commented code.

**Comment by c0rdis** [comment]
@Vincevrp done

**Pull request merged**
