### PR TITLE
Merge remote-tracking branch 'refs/remotes/privacytoolsIO/master'

### PR DESCRIPTION
**Pull request by LizMcIntyre**
Changed color of Bitcoin "Accepted" for StartMail from blue to green.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
It looks like [you've lost your actual changes](files) when trying to do a local merge...

I'd advise re-attempting your changes as follows:

```
git checkout master
git pull # update with latest changes
git checkout -b startmail-bitcoin-color-change
# make your changes
git add index.html
git commit
git push
```

Once you're done with that, you can open your PR from that `startmail-bitcoin-color-change` branch.

**Comment by LizMcIntyre** [comment]
Thanks. I'll try again.

**Comment by LizMcIntyre** [comment]
See pull request #229. This replace this failed pull request #228.

**Comment by Nightfirecat** [comment]
Looks good! You should be safe to close this PR now.

**Comment by LizMcIntyre** [comment]
Thanks!

**Pull request closed without merging**
