### PR TITLE
Matrix protocol / Riot.im client

### PR DESCRIPTION
**Pull request by sevengali**
### Description

Added Matrix and Riot.im to the worth mentioning list of the instant messaging section.

#433 #411 #220

First commit about ghostbin isn't present in this branch (is #435)

### HTML Preview

http://htmlpreview.github.io/?https://github.com/sevengali/privacytools.io/blob/sevengali-matrix/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
```html
<li><a href="https://matrix.org/">The Matrix protocol</a> and it's various clients such as <a href="https://about.riot.im/&gt;Riot.im&lt;/a&gt;. A successor of XMPP.&lt;/li&gt;&#10;&#9;&#9;&lt;/ul&gt;&#10;&#10;&#9;&#9;&lt;h3&gt;Related Information&lt;/h3&gt;&#10;&#9;&#9;&lt;ul&gt;&#10;&#9;&#9;&#9;&lt;li&gt;&lt;a href=" https:="" motherboard.vice.com="" read="" ricochet-encrypted-messenger-tackles-metadata-problem-head-on"="">Ricochet, the Messenger That Beats Metadata, Passes Security Audit | Motherboard</a></li>
```

**Comment by Shifterovich** [comment]
> <li><a href="https://matrix.org/">The Matrix protocol</a> and it's various clients such as <a href="https://about.riot.im/>Riot.im</a>. A successor of XMPP.</li>

The HTML seems correct, though. Maybe an issue with the preview website?

**Comment by sevengali** [comment]
Error was a missing "

    <a href="https://about.riot.im/>

**Comment by Shifterovich** [comment]
@beardog108 Merge?

**Pull request merged**
