### PR TITLE
add Radicale to the calendar and contacts section

### PR DESCRIPTION
**Pull request by NeverDucky**
### Description
discussion [here](https://www.reddit.com/r/privacytoolsIO/comments/88bt1n/secure_service_for_syncing_contactcalendar/dwkbb8f/)

### HTML Preview

*Replace [GITHUB_USERNAME] with your GitHub username and [BRANCH] with the branch name.*

http://htmlpreview.github.io/?https://github.com/neverducky/privacytools.io/blob/master/index.html#calendar_contacts

### CODE REVIEW

**Comment by Hillside502** [comment]
https://radicale.org/ throws this error:-
`radicale.org uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN `

So, the link needs to be http://radicale.org/

**Comment by NeverDucky** [comment]
okay but before this is merged I'd consider keeping the link https anyway. The error thrown is due to the cert being given by github even though the domain is custom. Arguably proceeding using the site over https knowing this is safer than using the site over http.

**Comment by Hillside502** [comment]
No way!

The radicale.org owner needs to get a cert.  Clearly, he/she is using HTTPS for site management, but (wrongly) thinks that HTTP is good enough for the punters.

Maybe, radicale dev should correct the error **before** the merge.

**Comment by NeverDucky** [comment]
perhaps it should link to https://github.com/Kozea/Radicale/wiki/Simple-installation instead?

**Comment by Hillside502** [comment]
> never mind I don't think the site is hosted on github so I don't even know why they're using a github cert

It is!
https://iplookup.flagfox.net/?ip=192.30.252.153&host=radicale.org
https://www.shodan.io/host/192.30.252.153

> The domain name is an alias for a web site whose main name is different, but the alias was not included in the certificate by mistake. 

https://www.ssllabs.com/ssltest/analyze.html?d=radicale.org

**Comment by NeverDucky** [comment]
ah well I can't seem to find where, or I would link the GitHub Pages site directly

**Comment by Hillside502** [comment]
Don't worry.  The problem is down to the radicale dev not configuring the website correctly.

**Comment by NeverDucky** [comment]
closing PR and will reopen because I need to change the branch name and github doesnt make it easy

**Pull request closed without merging**
