### PR TITLE
Reinstate DNSCrypt

### PR DESCRIPTION
**Pull request by NPN**
### Description

Add back DNSCrypt, as per discussion in #384. List of platforms has also been updated.

We may also want to change the logo, as the current one does not match the one on the website.

### HTML Preview

http://htmlpreview.github.io/?https://github.com/NPN/privacytools.io/blob/reinstate-dnscrypt/index.html

### CODE REVIEW

**Comment by g-monk** [comment]
Question: As you guys know I’m new and learning, I wanted to ask why DNSCrypt was removed in the first place.

**Comment by Shifterovich** [comment]
I think it was not being maintained or something like that.

**Comment by zero77** [comment]
@NPN 
I think DNSCrypt2 should be mentioned as it is fairly comprehensive now and it very stable.

**Comment by NPN** [comment]
@g-monk The issue I linked to above explains it. The basic reason is that v1 was dropped. Then, the website was redirected and eventually squatted. So, we removed it, because it seemed that the project might have been abandoned. Now, there's a new website and DNSCrypt-Proxy 2 is stable, so I think we should add it back.

@zero77 This change links to the DNSCrypt website, which has a big button that links you to "Implementations". DNSCrypt-Proxy 2 is at the top of that list. I think this is a better solution because it allows people learn about the project and then choose what implementation they want to use.

**Pull request merged**
