### PR TITLE
Free option column

### PR DESCRIPTION
**Pull request by OKNoah**
Adds “free option” column to emails and clarifies data.

### CODE REVIEW

**Comment by alexbooker** [comment]
First of all, thanks for the pull request -- your contribution is very
much appreciated.

I don't have time to check this out right now, but I will when I get
home. In all likelihood, I will submit a link to this pull request to
*r/privacytools* to get the communities feedback.


--
  Alex Booker
  alexbooker@fastmail.im
 
 
 
On Mon, Jan 18, 2016, at 06:08 PM, OKNoah wrote:
> Adds “free option” column to emails and clarifies data.


> 
> You can view, comment on, or merge this pull request online at:


> https://github.com/privacytoolsIO/privacytools.io/pull/26


> Commit Summary


>  * Removes Bitcoin support from Tutanota email
>  * Adds "free option" field to email providers
> File Changes


>  * *M* index.html[1]
    (105)
> Patch Links:


>  * https://github.com/privacytoolsIO/privacytools.io/pull/26.patch
>  * https://github.com/privacytoolsIO/privacytools.io/pull/26.diff
> —
> Reply to this email directly or view it on GitHub[2]. 


>  
 


Links:

  1. https://github.com/privacytoolsIO/privacytools.io/pull/26/files#diff-0
  2. https://github.com/privacytoolsIO/privacytools.io/pull/26

**Comment by OKNoah** [comment]
@alexbooker You are welcome. I didn't see your thread about it on reddit, but here's one: https://www.reddit.com/r/privacytoolsIO/comments/41td9l/proposed_site_update_more_email_provider/

**Comment by alexbooker** [comment]
Thanks for posting that thread. I will revisit it in a day or so when more people have had a chance to see it.

@privacytoolsIO, for such a significant change, I would really appreciate your input. Thanks.

**Comment by OKNoah** [comment]
By the way, here is a screenshot.

screen shot 2016-01-21 at 6 44 53 am

It's really not too big a change, just a new column and clarity on two of the other columns.

**Comment by alexbooker** [comment]
It's not a big change, you're right. I would still like to see some more support though.

As you can probably appreciate, it's not strictly up to me to make changes to the site. This is a community website after all.

Thanks for your patience. Believe me when I say I am giving this due consideration!

**Comment by OKNoah** [comment]
Any progress here?

**Comment by OKNoah** [comment]
Happy belated 1 month anniversary to this pull request!

**Comment by alexbooker** [comment]
I appreciate you **1,** taking the time to make these changes in the first place and **2,** diligently reminding me to tend to them. I cannot promise I will merge this but I do promise to evaluate it properly this evening, when I have time.

If I remember correctly, I have three concerns:

- I have to double check all your data
- I think there was a small issue with the [Bootstrap labels](http://getbootstrap.com/components/#available-variations) (not shown in your screenshot)
- [Not much engagement on Reddit](https://www.reddit.com/r/privacytoolsIO/comments/41td9l/proposed_site_update_more_email_provider/), but I agree this is a small and probably useful change

Thanks.

**Comment by alexbooker** [comment]
I apprecaite your contribution, @OKNoah but as it stands, there are a couple of problems with this pull request. I encourage you to fix them and will help you if you need. 

**Problem 1:** Your changes have caused the table to look quite messy:



Compare that screenshot of your fork to the current site:



**Problem 2:** The word _"No"_ should have a blue background like the other occurrences of the word:



**Problem 3:** Please avoid text in parentheses like _"(for donations)"_. It makes the table appear more complicated than it needs to be. 

Thanks :smile:!

**Comment by privacytoolsIO** [comment]
Sorry @OKNoah, like @alexbooker pointed out it gets too messy. I'd like to keep it simple. But I also appreciate the efforts. Thanks, guys!

**Comment by OKNoah** [comment]
@privacytoolsIO @alexbooker All fixes submitted.

Agreed that it needs to be simple, but not so much that it becomes misleading. I spent a lot of time reading about or signing up for these services only to find they didn't really meet the features the table implied. Hopefully these changes save others time.

**Comment by alexbooker** [comment]
> @privacytoolsIO @alexbooker All fixes submitted.

@OKNoah, I cannot see any updates to this pull request, nor can I see a new pull request :confused: 

@privacytoolsIO, I'm a tiny bit confused. Are you in support of this update or not?

**Comment by privacytoolsIO** [comment]
@alexbooker Sorry, should've made myself more clear. I'm not in support of the update because of the issues you also pointed out.

**Comment by alexbooker** [comment]
@privacytoolsIO Thanks for clarifying.

Would you be on board if @OKNoah _addressed_ the issues I mentioned (i.e. if @OKNoah added a simple free column _only_)?

**Comment by OKNoah** [comment]
@alexbooker I believe I must start a new PR because this one was closed prematurely.

**Pull request closed without merging**
