### PR TITLE
Add a Clearnet URL and Darknet URL to email provider table

### LINKED ISSUE #165: add Tor Link to ProtonMail
Since ProtonMail has recently launched their own .onion domain in Tor Network [1] to add an extra security layer [2] 
Maybe make sense to add the link somewhere?

Regards

[1] https://protonmail.com/tor
[2] https://protonmail.com/blog/tor-encrypted-email/

### PR DESCRIPTION
**Pull request by mitchellcash**
Fixes #165.

If you wish to view the diff without whitespace add `?w=1` to the end of the URL. Like [this](https://github.com/privacytoolsIO/privacytools.io/pull/166/files?w=1).

### CODE REVIEW

**Comment by mitchellcash** [comment]
Fixed merge conflicts

**Comment by Shifterovich** [comment]
I'm not so sure about the whitespaces. They don't seem to affect the file size, though.

**Comment by e5f3c2ea895af0f27667** [comment]
@mitchellcash Putting a "Darknet URL" column shouldn't be the way to do that, especially considering that next-gen onion services will have 52 characters. There's certainly a much better UX solution (adding an onion icon near Protonmail.ch?).

**Comment by kewde** [comment]
@e5f3c2ea895af0f27667 I like the idea you proposed, design wise it is a lot better. I'd use an official Tor logo to make it more obvious tho. Or simply the text "onion"..

**Comment by mitchellcash** [comment]
@e5f3c2ea895af0f27667 @kewde good thinking, I've made the applicable changes. It now looks like the below, what are your thoughts?

email-provider-clearnet-darknet-url

**Comment by mitchellcash** [comment]
I've now also added tooltips, so the user better understands where each URL takes them to.

email-provider-clearnet-darknet-url-2

**Comment by kewde** [comment]
@mitchellcash That does look better! Whatcha think @Shifterovich?

**Comment by Shifterovich** [comment]
I'd perhaps keep the clearnet URL as text. How would that look like @mitchellcash?

**Comment by mitchellcash** [comment]
@Shifterovich what do you think?

email-provider-clearnet-darknet-url-3

I think I personally like the my other mock ups. But maybe I can play around with this some more.

**Comment by mitchellcash** [comment]
Or...

email-provider-clearnet-darknet-url-4

**Comment by Shifterovich** [comment]
My opinion is either two buttons or a button for clearnet and text for darknet. Could you also make that one?

**Comment by kewde** [comment]
The buttons works nicely, I've resolved the merge conflicts.

I tried moving these svgs into their own file :| The  tags didn't work.

**Comment by kewde** [comment]
#248 fixed

**Comment by mitchellcash** [comment]
@kewde apologies, I totally missed this. I just happened to be browsing the website and was thinking - wait, those changes look like my forgotten pull request!

Thanks for fixing this up and getting it merged :)

**Pull request closed without merging**
