### PR TITLE
Replace GNU Social with Mastodon

### PR DESCRIPTION
**Pull request by nikhiljha**
## Description
Mastodon is significantly easier to set up, easier to use, more user friendly, and has a larger community than GNU Social and all the other alternatives. _Non-technical visitors of privacytools.io will probably be discouraged by all the "here just set up a server and compile this"_ - so having the easy to use one first is likely the best option.

I also made some quality of life adjustments, such as adding `.DS_Store` to the `.gitignore` so that Mac users can contribute without accidentally checking in useless files, as well as added instructions on how to build the HTML files into the README.

## Screenshots

screen shot 2018-11-22 at 7 19 06 pm

### CODE REVIEW

**Comment by nikhiljha** [comment]
Just added some organizational changes.

Previously we had the software dropdown sorted seemingly at random. Some things weren't even listed in the dropdown, and many were not in the right location...

screen shot 2018-11-22 at 7 45 42 pm

Now all of that is fixed!

screen shot 2018-11-22 at 7 44 37 pm

Additionally, the Key Disclosure section was randomly in the middle of all the software and does not appear to be linked to from anywhere. I moved it higher up the page so it fits better and is more visible (it seems important).

**Comment by nikhiljha** [comment]
Apologies for turning this into a giant housekeeping PR, feel free to cherrypick commits and decide on the other ones later (though I think it's a no-brainer to merge).

**Comment by Shifterovich** [comment]
Thanks a lot. All of these are issues which majorly irritated me.

**Comment by Shifterovich** [comment]
Regarding the README update, could you please take a look at this? https://github.com/privacytoolsIO/privacytools.io/issues/609#issuecomment-441092679

bundle install took like 5 minutes on my Ubuntu 18.04, but simply changing the gem from gh pages to jekyll works too and lets me start working in no time.

**Comment by nikhiljha** [comment]
Hmm, I think the two gems are not guaranteed to function identically ([as per the Jekyll website](
https://jekyllrb.com/docs/github-pages/#the-github-pages-gem))...

```
Using it in your projects means that when you deploy your site to GitHub Pages, you will not be caught by unexpected differences between various versions of the gems.
```

So just for the future it might not be worth suggesting that contributors do this. At the very least, I personally didn't mind waiting the 2-3 minutes running a `bundle install`.

**Comment by nikhiljha** [comment]
@Shifterovich Also, are you on IRC/can I contact you somewhere else? I have a few ideas for changes I'd want to discuss but I don't think they belong here.

**Comment by Shifterovich** [comment]
t.me/Shifterovich or Shifterovich on Signal assuming you don't need my number or Shifterovich on Riot.im. I can do IRC/XMPP later today or tomorrow.

**Pull request merged**
