### PR TITLE
Added ExifCleaner to the Metadata Removal Tools section on the Productivity Tools page

### PR DESCRIPTION
**Pull request by szTheory**
## Description

Resolves: PR requested by @blacklight447-ptio  https://github.com/privacytoolsIO/privacytools.io/issues/1729

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: 
https://deploy-preview-1802--privacytools-io.netlify.com/software/productivity/#metadata-removal-tools

* Code repository of the project (if applicable):
https://github.com/szTheory/privacytools.io

### CODE REVIEW

**Comment by dngray** [comment]
Thanks for helping, it's nice when people  open PRs instead of making issues. Gives us time to work on the more major facelifts!

**Comment by dngray** [comment]
To optimize an SVG image add it to a new canvas. Make the image  128x128px then export like so:

optimize_svg

**Comment by szTheory** [comment]
@dngray Ah, I used an online tool to "convert" the PNG to an SVG since I don't have a vector graphic. Any suggestions on a tool that would create a true SVG by tracing the edges? Or a way to easily create an SVG from scratch? If not I will look into it soon and figure something out.

**Comment by dngray** [comment]
> Any suggestions on a tool that would create a true SVG by tracing the edges? Or a way to easily create an SVG from scratch? If not I will look into it soon and figure something out.

Yes. Inkscape https://inkscape.org/

**Comment by szTheory** [comment]
Whew, that was quite the journey. I tried a lot of different tools but the only one I had success with for generating an auto traced SVG was https://vectorizer.io, a free tool (Inkscape's auto trace in 1.0 beta was broken for me when I tried it on a Mac). I then exported it as an optimized SVG in Inkscape using the settings you recommended above. I rebuilt the Jekyll site and it still looks good to me (see screenshot below).
privacytools updated with svg

Thanks for the help! Let me know if you need anything else.

**Comment by blacklight447-ptio** [comment]
Thanky you @szTheory ! Im currently on my phone so i can't give it proper review, i will do so on my laptop either tonight or tommorow morning! :)

**Comment by dngray** [comment]
I assume you don't have the original artwork in vector format? If not, we might try re-creating it manually. I guess the benefit would be you'd then have a vector image.

Of course you'd want to then update the usage everywhere to use the same picture.

The problem with tracing tools is they're not perfect and lead to ugly lines:

eg1

eg2

This leads to very large SVG images, eg this SVG is 78kb when compared to others under 10Kb as it contains a lot of useless data.

**Comment by szTheory** [comment]
Sorry yeah I don't have the original vector and I don't know how to use vector art tools. Even though I know Photoshop, looking at Inkscape or Illustrator always confuses me and I don't even know where to begin when I open those programs up. So I'd have to run through a video tutorial series or something to learn how to trace the lines and do the fills. I'm sure it would be manageable, just another thing to do. Maybe I can even find a website for a graphic designer to do it for me.

**Comment by dngray** [comment]
We've put our master designer @dawidpotocki on this, and I think he might have come up with something...

**Comment by dawidpotocki** [comment]
There you go:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="512" height="512" version="1.1" viewBox="0 0 135.46666 135.46667" xmlns="http://www.w3.org/2000/svg"><g transform="translate(0,-161.53331)"><g transform="translate(-301.68598,22.068187)"><circle cx="369.41931" cy="207.19846" r="67.73333" fill="#521737" stroke-width=".71865606"/><path transform="matrix(.26458333 0 0 .26458333 301.68598 139.46512)" d="m265.99414 65.179688v0.0078c1.89014 2.437963 3.02734 5.580618 3.02734 9.021484v195.236338c19.42623 3.38842 50.3142 16.13793 55.4043 62.42188l0.26367 2.37695 1.95117 17.61133h-2e-3l10.25195 92.56641h-161.80664l64.78516 67.07031c5.41183 0.44356 10.7018 0.40924 16.13086 0.50781 6.04218 3e-4 12.08235-0.21339 18.10938-0.64062 8.51338-0.60344 16.99168-1.63363 25.40234-3.08399 8.41069-1.45122 16.743-3.32188 24.9668-5.60547 8.22429-2.28253 16.32985-4.97422 24.28515-8.0664 7.9553-3.09309 15.75067-6.58326 23.35742-10.45508 7.60634-3.8716 15.01342-8.1208 22.19532-12.73242 7.18227-4.61141 14.13034-9.57933 20.8164-14.88477 6.68584-5.30547 13.10178-10.94223 19.22461-16.88867 6.12253-5.94637 11.94494-12.19481 17.44336-18.72266 5.49857-6.528 10.66694-13.32681 15.48633-20.37109 4.8192-7.04432 9.28313-14.32426 13.375-21.81445 4.09206-7.49042 7.80707-15.18144 11.13086-23.04297 3.32326-7.86157 6.24967-15.885 8.77148-24.03907 2.52227-8.15402 4.63642-16.42785 6.33203-24.79296 0.0435-0.28271 0.12174-0.53757 0.16407-0.82032zm-119.27539 111.205082c-3e-3 20.21693 16.3866 36.60692 36.60352 36.60546zm36.60352 36.60546c-20.21616-1e-3 -36.60496 16.38735-36.60352 36.60352 9.4e-4 -4.2e-4 50.20498 51.01711 50.20498 51.01711 12.09886-18.15775 28.86594-28.06681 41.94895-30.34882zm-36.60352 36.60352c1e-3 -20.21617-16.38736-36.60498-36.60352-36.60352z" fill="#351228" stroke-width=".98461533"/><g transform="matrix(.98461542 0 0 .98461542 4.6413108 4.2297091)" fill="#fff"><path d="m370.47466 153.51264c-1.94082 0-3.50263 1.68459-3.50263 3.77703v54.44525c0 2.09246 1.56181 3.77703 3.50263 3.77703s3.50262-1.68457 3.50262-3.77703v-54.44525c0-2.09244-1.5618-3.77703-3.50262-3.77703z" stroke-width=".62165785"/><path d="m341.11212 184.74659a9.8352962 9.8353025 0 0 1-9.83597 9.83597 9.8352962 9.8353025 0 0 1 9.83597 9.83598 9.8352962 9.8353025 0 0 1 9.83597-9.83598 9.8352962 9.8353025 0 0 1-9.83597-9.83597z" fill="#fff" stroke-width=".63311845"/><path d="m401.70726 203.65527a8.345514 8.345514 0 0 1-8.34607 8.34609 8.345514 8.345514 0 0 1 8.34607 8.34607 8.345514 8.345514 0 0 1 8.34608-8.34607 8.345514 8.345514 0 0 1-8.34608-8.34609z" fill="#fff" stroke-width=".53721792"/><path d="m370.47466 153.51263v61.99953c-1.94082 0-3.50264-1.68458-3.50264-3.77704v-54.44546c0-2.09243 1.56182-3.77703 3.50264-3.77703z" stroke-width=".62165785"/></g><path d="m369.41638 155.38061v61.04569c1.91096 0 3.44875-1.65866 3.44875-3.71893v-53.60784c0-2.06023-1.53779-3.71892-3.44875-3.71892z" fill="#dfdfe0" stroke-width=".61209393"/><path d="m369.41621 210.44331c-3.32016 0-16.37425 1.06008-18.10832 16.82794l-3.29739 29.78046h42.8114l-3.29738-29.78046c-1.73408-15.76786-14.78816-16.82794-18.10831-16.82794z" fill="#f8d057" stroke-width=".56530839"/><path d="m351.30821 227.27129c1.73408-15.76786 14.78801-16.82774 18.10817-16.82774v46.60802h-21.40587z" fill="#f8d057" stroke-width=".56530839"/><path d="m351.23822 227.90049 18.17814-3e-5 1e-5 4.65963h-18.6938z" fill="#e97043" stroke-width=".2573376"/><path d="m387.52452 227.27129c-1.73407-15.76786-14.788-16.82774-18.10816-16.82774v46.60802h21.40587z" fill="#f2b55a" stroke-width=".56530839"/><path d="m387.59419 227.90049h-18.17782v4.65963h18.69381z" fill="#a15439" stroke-width=".2573376"/></g></g></svg>
```

**Comment by szTheory** [comment]
@dawidpotocki Thank you so much, it looks great!

**Pull request merged**
