### PR TITLE
Add EasyCrypt to Privacy-Conscious Email Providers list

### PR DESCRIPTION
**Pull request by ezcdev**
### Description

Adding EasyCrypt to Privacy-Conscious Email Providers list

### HTML Preview

http://htmlpreview.github.io/?https://github.com/ezcdev/privacytools.io/blob/master/index.html#email

### CODE REVIEW

**Comment by Shifterovich** [comment]
@C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N Thoughts?

**Comment by bakku** [comment]
It's not really an email provider is it? Feels like this should be listed under the `Privacy Email Tools`. Furthermore every email I type in seems to be not working without any feedback why.

**Comment by Shifterovich** [comment]
It is not. I agree that's a better category. And it did work for me.

**Comment by ghere** [comment]
If something is not working please write to support@easycrypt.co. Note that JS must be enabled and only the following browsers are supported: Firefox, Chrome, Safari, Tor.

**Comment by ghere** [comment]
Why EasyCrypt team opines that this should be in the email category is described [here](https://www.reddit.com/r/privacytoolsIO/comments/6soqi3/were_considering_adding_easycrypt_to_the_ptio/dljv3jf/).

**Comment by Hillside502** [comment]
https://easycrypt.co/ contains the tracker `stats.wp.com`

**Comment by Shifterovich** [comment]
> Why EasyCrypt team opines that this should be in the email category is described here.

EasyCrypt is a tool, not an email provider.

**Comment by Shifterovich** [comment]
Also it's a new tool. Closed-source backend + no established trust.

**Comment by Hillside502** [comment]
Further to my comment above, https://easycrypt.co/ also uses `google-analytics.com`

So much for privacy!

**Comment by ghere** [comment]
We use GA to measure statistics of visits to our informational website, not to our email privacy service. 

You do not need to go to the website to sign up or to use the service, the signups/logins are at https://webmail.easycrypt.co/login/ and at webmail.ezcrypt2dgcicxqj.onion for https and Tor hidden service sites, respectively. No GA or even our internal user data logging there.

**Comment by Hillside502** [comment]
@ghere 
How about?
Web Analytics - PRISM Break
https://prism-break.org/en/all/#web-analytics

**Comment by ghere** [comment]
Yep these are good solutions. When we have more resources we'll move away form GA whos only attraction is that it is free and quick to implement. For now, faced with the choice where to put our limited resources, we put them in enhancing the security of the EasyCrypt service, not of the informational website.

**Comment by Shifterovich** [comment]
I suggest adding it in the same way as Mail-in-a-Box. Put EC below MiaB.

**Comment by ghere** [comment]
>I suggest adding it in the same way as Mail-in-a-Box. Put EC below MiaB.

This is definitely not in the same category as MiaB. EasyCrypt is a service provider that provides privacy services comparable to ProtonMail, Tutanota and Mailfence.

**Comment by Shifterovich** [comment]
It's a tool, not a provider.

**Comment by Shifterovich** [comment]
#### u/EasyCrypt•27 minutes ago

Hi Shifterovich,

I suggest that we take the discussion of whether EasyCrypt is a tool or a service provider off GitHub and complete it here.

EasyCrypt is definitely a service provider. We run the service from our servers in Switzerland. The service is personal, we manage user accounts and their encryption keys, and provide essentially the same function as other encrypted email providers except we allow them to use their existing email address and communicate with external PGP users. I do not understand why you classify, say, ProtonMail or Tutanota as a service provider but EasyCrypt as a "tool".

EasyCrypt

-----

#### u/Shifterovich•just now

> I suggest that we take the discussion of whether EasyCrypt is a tool or a service provider off GitHub and complete it here.

Disagree, we should discuss that publicly.

> I do not understand why you classify, say, ProtonMail or Tutanota as a service provider but EasyCrypt as a "tool".

ProtonMail provides an email address, they're an email provider. EC provides encryption for an existing email address, EC is a tool like Enigmail.

EC is a provider only if Enigmail is a provider. A server-side does not make you a provider. Closed-source backend doesn't make you a provider.

**Comment by ghere** [comment]
>EC is a provider only if Enigmail is a provider.
I disagree. Enigmail is a piece of software installed on a PC that leaves the key management burden on the user (which is precisely why so few people use PGP). This is definitely not a service. 

EasyCrypt provides a service to the user that frees the user from the need to install stuff on his PC and from doing key management. Which is why it is a service provider.

>Closed-source backend doesn't make you a provider.
Then why does PTIO list other closed source backend services as "providers"?

**Comment by Shifterovich** [comment]
> > Closed-source backend doesn't make you a provider.
>
> Then why does PTIO list other closed source backend services as "providers"?

False cause. Listing providers that have a closed-source backend doesn't imply that having a closed-source backend makes you a provider.

It might be an online service, but how is it an email provider?

You want to have a superior position in the provider table, yet you're a new service with no established trust, closed-source backend and not enough resources to run an analytics platform?

**Comment by Shifterovich** [comment]
Also in the other thread you said

> I beg to differ. Relying on trust in service providers is a really bad practice.

On what basis should we add you then?

**Comment by bakku** [comment]
> I suggest adding it in the same way as Mail-in-a-Box. Put EC below MiaB.

I second that

> This is definitely not in the same category as MiaB.

I don't really think that MiaB is in any category. There is just a paragraph for MiaB on its own without any specific category. You might have a point that EC is not a `Privacy Email Tool`, but when you emphasis on the more or less important detail, that it is not a tool, because it is managed server side, then we should also emphasis on the more or less important detail that it is not really an `Email Provider`, but it uses an existing email from a different provider.

**Comment by Shifterovich** [comment]
> I don't really think that MiaB is in any category. There is just a paragraph for MiaB on its own without any specific category.

Exactly. It allows for an image and a long description. It's better than one-line descriptions of Privacy Email Tools and highlights that it's different than the other things mentioned in that section, the same way as MiaB.

**Comment by ghere** [comment]
>I don't really think that MiaB is in any category.

Of course it is. The category is spelled out in the heading: "Become Your Own Email Provider". This has absolutely nothing in common with what EasyCrypt does.

**Comment by bakku** [comment]
Have a look here: https://www.privacytools.io/#addons and imagine MiaB is `Privacy Badger` and EC is `uBlock Origin`. This is the way EC should be listed here...

**Comment by ghere** [comment]
>Have a look here: https://www.privacytools.io/#addons and imagine MiaB is Privacy Badger and EC is uBlock Origin. This is the way EC should be listed here...

I disagree. EC is not an extension or an add-on. It is a stand-alone email privacy service.

Possibly a new category could be created: "Email privacy services". We can provide the suggested headings for parameters of such services (eg which email services are supported; is the encryption end to end; kind of encryption supported;  is it available as a Tor/I2P hidden service; does it require installation; does it use JS etc.)

**Comment by bakku** [comment]
> I disagree. EC is not an extension or an add-on. It is a stand-alone email privacy service.

MiaB is not an extension or an add-on as well but still listed this way...This way of listing does not have to do anything with extensions or add-ons.

> Possibly a new category could be created

Maybe...but a new category for only one service sounds overkill. Rather have it below MiaB with an expressive headline and description.

**Comment by Shifterovich** [comment]
>The category is spelled out in the heading: "Become Your Own Email Provider"

You're very confused. That's a heading, not a category

> > This is **the way** EC should be listed here...
>
> I disagree. EC is not an extension or an add-on. It is a stand-alone email privacy service.

You're misinterpreting what's been said.

----

Whether you like it or not, closed-source services require trust. Adding a service like yours is usually a matter of a proposal, approval, and merge.

By your senseless arguing over things you misinterpret, you're building everything but trust (which you lack, by the way).

**Comment by ghere** [comment]
>By your senseless arguing over things you misinterpret, you're building everything but trust (which you lack, by the way).

I like your style.

**Comment by kewde** [comment]
In a strict sense, they aren't an email provider. But they aren't quite an email tool either (they provide a service that: stores your keys and encrypts your email). A tool (in my opinion) is a piece of software that I can store on my computer and use at my own discretion without requiring third parties.

I have no objection listing them with the email providers due to lack of a better category to put them on.
A somewhat better description of them is "email encryption service provider".

**Comment by Shifterovich** [comment]
How is listing them as a provider more okay than listing them as a tool, if they're neither?

Like I said, it puts them at a superior position in the table while not being an email provider.

**Comment by kewde** [comment]
> How is listing them as a provider more okay than listing them as a tool, if they're neither?

There is no clearcut category for EC but they are definitely more of a service provider than a tool. If we're rejecting them for merely not "fitting" in the existing boundaries of our title/description for that section then we could just rename the section to have a broader title.

Note: I'm not a fan of the whole email provider section or closed-source applications in general (encryption and key storage must happen locally IMO). If it were up to me the whole section would be gone :P At least they are better than Gmail et al.

> Like I said, it puts them at a superior position in the table while not being an email provider.
Fair point. I'm just glad to see an onion domain. (And IMO all projects that provide an onion domain can have superiority in a table)

**Comment by Shifterovich** [comment]
> And IMO all projects that provide an onion domain can have superiority in a table

Yes, but if you look at the pull requests, the values were "Unlimited" for storage, etc.

> Note: I'm not a fan of the whole email provider section or closed-source services in general (encryption and key storage must happen locally IMO). If it were up to me the whole section would be gone :P At least they are better than Gmail et al.

The point is not to recommend Snowden-level tools, but to cover the whole spectrum of threat models. ProtonMail for fast and usable crypto, local GPG in an offline VM for maximum security when it's possible.

**Comment by kewde** [comment]
> Yes, but if you look at the pull request, the values were "Unlimited" for storage, etc.

Ahh, I get his reasoning but not applicable" is better. Anyways, unless he re-opens the PR then I'm not really going to put more time into it.

> The point is not to recommend Snowden-level tools, but to cover the whole spectrum of threat models. ProtonMail for fast and usable crypto, local GPG in an offline VM for maximum security when it's possible.

I know, that's why I can live with it. Every step in the right direction is better, even if it's a small one.

**Comment by ghere** [comment]
@kewde 
> There is no clearcut category for EC but they are definitely more of a service provider than a tool. If we're rejecting them for merely not "fitting" in the existing boundaries of our title/description for that section then we could just rename the section to have a broader 
This was precisely my opinion and point.

> unless he re-opens the PR then I'm not really going to put more time into it.
We closed the PR because it resulted in vitriolic bashing of EasyCrypt rather than in constructive discussion. This included the attempt to push EasyCrypt _service_ into the _Tool_ category, comments about the resulting "superior position" in the encrypted email services table (should not the table just provide the _correct_ information and let the user decide what is superior to what according to his needs, convenience and threat model, rather than block information about features of EasyCrypt that make it superior to ProtonMail, like no limit on messages and ability of full bibirectional communication with any PGP user rather than putting the user in the walled ProtonMail garden?), telling us that we are not to be trusted etc. So we closed the pull request to put an end to all this biased bashing that led nowhere. Please give me a good reason to reopen the PR Iin view of all this and then possibly we will.

**Comment by ghere** [comment]
@Shifterovich 

> Like I said, it puts them at a superior position in the table while not being an email provider.


> ProtonMail for fast and usable crypto, local GPG in an offline VM for maximum security when it's possible.

I thought this was supposed to be a discussion of EasyCrypt's pull request and verification that information provided in the modified PR about EasyCrypt is correct. I was not aware that the intent was to protect the superior position of ProtonMail in the comparison table. EasyCrypt _is_ superior to ProtonMail in its openness (communication with any PGP user and not a walled garden), unlimited messages, inherent ability of data liberation and import/export of PGP keys, PGP/MIME support and more.

If you would tell us in advance that you want to preserve the superior position ov ProtonMail in the comparison table no matter what, we would not have bothered to open the PR.

**Comment by Shifterovich** [comment]
> biased bashing

Let's check the facts.

**Falsely superior position**: True, since it's not an email provider yet has the best values of all the providers in the table

> I thought this was supposed to be a **discussion of EasyCrypt's pull request and verification that information provided in the modified PR about EasyCrypt is correct**.

Yes, the information provided in the PR is incorrect. 

> I was not aware that the **intent was to protect the superior position of ProtonMail** in the comparison table.

How did you come up with that?

> **EasyCrypt is superior to ProtonMail** in its openness (communication with any PGP user and not a walled garden), unlimited messages, inherent ability of data liberation and import/export of PGP keys, PGP/MIME support and more.

Yeah, except it's not an email provider and is extremely inferior in the lack of any built trust. GPG IS SUPERIOR TO EASYCRYPT --- is this how you compare stuff?

-------

Like I already said, I'd have no problem adding you, if you:

- used the correct category
- were a trusted service and/or were actually interested in working out the changes instead of pointlessly arguing and talking shit about the website you want your service added to.

**Comment by ghere** [comment]
@Shifterovich 

> Let's check the facts.

> used the correct category

So the only "incorrect fact" provided by EasyCrypt that you can come up with is the moot point of this thread? This is not an incorrect fact, this is _your opinion_, which is being disputed on this thread at length.

If this is how you "check the facts" you should submit a PR for replacement of the comparison table title by  "Shifterovich's favorite email providers".

**Comment by Shifterovich** [comment]
lol.

I won't waste any more time here.

Not gonna trust someone who doesn't have any sense of logic whatsoever with my email crypto.

> this is your opinion

"EasyCrypt is an email provider."

True or false?

---

### EasyCrypt will not be added

Good luck at [nylira/prism-break](https://github.com/nylira/prism-break).

Sent with [ProtonMail](https://protonmail.com) Secure Email. :)

**Comment by ghere** [comment]
@shifteroviich

That EasyCrypt won't be added and your personal reasons for not letting it be listed were  abundantly clear to us weeks ago, which is why  we canceled our PR at that time. 

The only remaining question is why you needed to run the farce of "community comments" in the first place,  and what it says about how privacytools.io makes its decisions.

**Comment by kewde** [comment]
@ghere @Shifterovich 

There are multiple possible approaches to adding EC to privacytools. 

1) We can add them to the table of email providers.
We can list EC under ProtonMail and have "N/A" for the fields that do not apply (storage is the only one?).
This is regardless of any "technical superiority" but because of the mere fact that we're comparing apples and oranges.
They provide an onion domain, which is IMO a valuable argument for putting them higher on the list.
Other email providers might see the benefit of creating an onion domain for their service if they see that we treat them differently.

2) We make a whole new category and search for projects/services that do the same thing EC is doing.
This is a lot of work and I'm not aware of any projects like them.

I opt for option number one, it's easier and less work. The second option arguably benefits EC even more.

**Comment by ghere** [comment]
@kewde  @Shifterovich

Either of the suggested compromises/approaches would be fine with us. 

We would also appreciate an opportunity to straighten out our differences with Shifterovich which, at least on our side, admittedly went too far...

**Comment by Shifterovich** [comment]
I vote for not adding them at all.

Like I said

> Not gonna trust someone who doesn't have any sense of logic with my email crypto.

-------
> If you would tell us in advance that you want to preserve the superior position of ProtonMail in the comparison table no matter what, we would not have bothered to open the PR.

> We closed the PR since the discussion was deliberately biased towards preserving the superior position of ProtonMail by excluding from the comparison table any data about features in which ProtonMail may be inferior to EasyCrypt

With our visitors' best interest in mind, I'm strongly against adding EasyCrypt.

**Comment by Shifterovich** [comment]
@kewde The most critical part is trust. I don't trust a service that's attacking the team of the site they want to be added to with lies after it's pointed out that their pull request is pure snake oil.

**Comment by kewde** [comment]
@Shifterovich 

I should've been more clear, I was discussing the potential approaches of how we could add them.
We might see more services like them, we need to have a way to deal with those.  I use them as a convenient example. They way I see it, this  controversy started around the question "how we should approach this type of service/toolish provider" :stuck_out_tongue: 

Anyways, the whole section is kinda snake oil, I only kinda "trust"/know tutanota and protonmail on the list. I have no objection adding them there. Ofcourse they were going to present their project in the best way possible, and argue their case to us.. It's our job to filter out the bullshit and check the facts to the extent that we can. Also using ProtonMail as an example, and then taunting them by replying with ProtonMail didn't inspire confidence on our neutrality.

**Comment by Shifterovich** [comment]
> A tool (in my opinion) is a piece of software that I can store on my computer and use at my own discretion without requiring third parties. So I think we should classify them as a service provider.

Yes, but it's more of a tool than an **email** provider.

> Also using ProtonMail as an example, and then taunting them by replying with ProtonMail didn't inspire confidence on our neutrality.

That was a response to the allegations that we're protecting ProtonMail's superiority in the table :P

**Comment by kewde** [comment]
> Yes, but it's more of a tool than an email provider.

I can't download it and use it at my own discretion. I think they're more related to an email provider than a tool to be honest

> That was a response to the allegations that we're protecting ProtonMail's superiority in the table :P

I know you're kidding, taunting them a bit but inb4 privacytools.io bribed by protonmail shitstorm.

**Comment by Shifterovich** [comment]
> I can't download it and use it at my own discretion. I think they're more related to an email provider than a tool to be honest

Tools **can** be online, but email providers **must provide an email address**.

**Comment by kewde** [comment]
>  Tools can be online, but email providers must provide an email address.

We don't have to work within the confined boundaries of our existing headers.
For all I care
```
Privacy-Conscious Email Providers -> Privacy-Conscious Email Providers & Email Encryption Services
```

**Comment by Shifterovich** [comment]
imo this is a tool https://atelier.u-sub.net/srt2vtt/

**Comment by kewde** [comment]
> imo this is a tool https://atelier.u-sub.net/srt2vtt/

That website provides you a service. The source code is available tho, so they also provide a tool (unlike EC).

**Comment by Shifterovich** [comment]
Whether the source is available or not is irrelevant to being a tool.

Even the website states that it's a tool.

**Comment by Shifterovich** [comment]
https://3142.nl/latex-diff/ is this a service?

Is this web tool a service? http://aesencryption.net/

**Comment by kewde** [comment]
They are just services that present themselves as tools.. 3142 provides you the service of a latex-diff. AESEncryption.net provides you with the service of AES encryption. If they suddenly close down their service then it is gone. Just because it has a user interface doesn't automatically make it a tool. I'll do a bit of English magic and call them toolish services.

The distinction is also made in our DNS section, DNSCrypt is a tool, the other is a service.
https://www.privacytools.io/#dns

**Comment by Shifterovich** [comment]
> Just because it has a user interface doesn't automatically make it a tool.

Just because it's not local doesn't make it not a tool.

I'll do a bit of English and say that EC is a servicish tool, and that even if they were services, they'd be *closer* to a tool than an email provider.

**Comment by kewde** [comment]
> Just because it's not local doesn't make it not a tool.

That's correct, but to be classified as a tool you must be _able_ to use it locally. A tool has independence. This discussion is like me: 'hey there is a taxi', and you're saying 'no that's a car'.
Every taxi is a car, but not all cars are taxis.

They're definitely not an email provider, but again we don't need to restrict ourselves to these imaginary boundaries. I'd rather not have these kind of services labelled under tools. The mail providers don't provide the same level of security I'd expect from a tool.

**Comment by Shifterovich** [comment]
Service/web tool is closer to a tool than to an email provider. imo implementing this kind of (web)tools/services the way MiaB is implemented is the best option.

**Pull request closed without merging**
