### PR TITLE
Added RetroShare as email alternative

### PR DESCRIPTION
**Pull request by dimqua**

### CODE REVIEW

**Comment by alexbooker** [comment]
Hi @dimqua,

Thanks for your contribution. Everything looks in order to me :+1:. All I would suggest is that you use the same description for both _RetroShare_ entries. At the moment you use this description for the email entry:

> cross-platform, secured and decentralized communication system.

And this description for the self-contained networks entry:

> Open Source cross-platform, Friend-2-Friend and secure decentralised communication platform.

In my opinion you should use the same description in both places for the sake of consistency. 

I'll leave this open for @privacytoolsIO to review and potentially merge when he/she has time.

Oh, and good call on changing _`retroshare.sourceforge.net`_ to _`retroshare.org`_.

**Comment by privacytoolsIO** [comment]
Thanks, guys.

"Oh, and good call on changing retroshare.sourceforge.net to retroshare.org."

I had to undo this, because retroshare.org redirects now to the sourceforge page.

**Comment by alexbooker** [comment]
I could have sworn it was the _other_ way around when I checked. Good catch.

**Comment by dimqua** [comment]
@privacytoolsIO RetroShare switching on GitHub right now. So retroshare.sf.net will be dead soon.

**Pull request merged**
