### PR TITLE
Add Hosting Section

### PR DESCRIPTION
**Pull request by asddsaz**
## Description
**Description**: Add Hosting Section

**What companies did you add?** : 

**General/BulletProof**: [BAHNHOF](https://www.bahnhof.net/page/vps).
**Colocating**: [DataCell](https://datacell.is/)
**Web/VPS** plug-and-play: [Orange Websites](https://www.orangewebsite.com/)

**I have a suggested change**! Great! Plz make a comment so that it may be reviewed. Edits from maintainers are welcomed.

Resolves: #none

### CODE REVIEW

**Comment by Shifterovich** [comment]
Now it looks good. :+1: Tomorrow I'll build it and will take a look at it.

**Comment by asddsaz** [comment]
@Shifterovich Aye, any updates? Did you build it? :)

**Comment by Shifterovich** [comment]
screenshot from 2018-12-05 21-45-42

Maybe add a worth mentioning section and add a link to the navbar?

**Comment by asddsaz** [comment]
@Shifterovich 

> Maybe add a worth mentioning section[....]

The private and secure hosting sphere is very small. I honestly don't know of any more than what are listed. Orange hosting is very plug-and-play (FYI, it does utilize [CPanel](https://en.wikipedia.org/wiki/CPanel)) while the other options are more for co-locating or VPS.
I did create a fork with Vikings.net, however it had some bugs (i'm a noob): https://htmlpreview.github.io/?https://github.com/asddsaz/privacytools.io/blob/hosting%2Bvikings/index.html

>  and add a link to the navbar?

It shows up for me?

**Comment by Shifterovich** [comment]
> I did create a fork with Vikings.net, however it had some bugs

Yeah, unfortunately it's not possible to preview Jekyll files like that. I might code a bot one day to add previews to pull requests.

> I'm a bit new to coding Jekyll. Is there like a file I need to edit?
> Super sorry for my noobish-ness. :)

No problem. When you look at the top of index.html, you can see that it uses the default layout. So when you go to _layouts/default.html, you can see the layout HTML file. You can edit the navbar there.

I'm thinking that we should update the contributing guidelines with more info, since we switched to Jekyll which is a bit more confusing to newbies.

**Comment by asddsaz** [comment]
@Shifterovich Ok, I added it to the navbar.
Thanks for your help! :)

**Pull request merged**
