### PR TITLE
Add a warning about GApps

### PR DESCRIPTION
**Pull request by hugoncosta**
### Description
Small alert in the Mobile OS area with concern to the use of apps made by Google.

### HTML Preview

http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-1/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
Maybe add a similar notice to Lineage too? IIRC it can be downloaded both with and without Google services.

**Comment by hugoncosta** [comment]
Changed everything. I was in doubt with the "are" too, since I wanted to make reference to the 3 alternatives, but in hindsight, it does sound better with "is".

The GApps warning is supposed to be to Android OS in general, since you have the option to install them on every distro.

**Comment by Shifterovich** [comment]
Been nearly a week, still no approval of another contributor. Merging.

**Comment by kewde** [comment]
Please ping me with @kewde in cases like these (or on IRC), I have tons of messages on github

**Pull request merged**
