### PR TITLE
Split All Services into Individual Pages

### PR DESCRIPTION
**Pull request by JonahAragon**
Thinking about splitting everything up into individual pages.

**To-do**

- [x] Ensure assets load from all pages.
- [x] Update navbar.
- [x] Remove services from index.
- [x] Add some cards/links on the homepage linking to these different pages.
   - [x] Consider making the homepage cleaner overall. Move some of the less immediately useful to a subpage and make clear links to all the different subpages.
- [x] Make each page have it's own `<title>`
- [x] Give each page better headers so they look nicer standalone.
- [x] Adjust the layouts/paddings a bit so the pages look better standalone.
   - All the headers site-wide should have better spacing, everything kind of looks smushed together.
- [x] Configure redirects from old anchor links to new permalinks.
   - We have to use Javascript (see #140) but @BurungHantu1605 wants this done :/
- [x] Create overview pages for the providers and software categories.
   - [x] `/providers/`
   - [x] `/software/`
   - Currently `/browsers/` and `/os/` have no subpages.

---

Commit `4cd2824` is live at https://dev-1.privacytools.io/index.html for testing.
Updated as of Apr 1, 5:33 PM CT

---

Resolves: #140, Resolves: #624, Related: #145

### CODE REVIEW

**Comment by BurungHantu1605** [comment]
Great job so far. 

> Create overview pages for the providers and software categories.

I'd give this a low priority. Same with the redirects, we can do that when everything else is done.

**Comment by JonahAragon** [comment]
The latest commit on here adds probably a better services page than I was planning, so this PR now closes #788 if merged.

**Comment by victorhck** [comment]
(sorry I edited the first comment by error. I left again like original)

**Comment by JonahAragon** [comment]
Geez, who *doesn’t* have permissions to edit my comments in this repo 😆

**Comment by temporarium** [comment]
It's easier to track content changes/modification when it's all one page.

Perhaps some kind of tagging system would be better.

**Comment by Shifterovich** [comment]
All content is added via pull requests. There's just a few of them per month.

**Pull request merged**
