### PR TITLE
Added social-share-link for Diaspora

### PR DESCRIPTION
**Pull request by FlxAlbroscheit**
Refers to #127

### CODE REVIEW

**Comment by privacytoolsIO** [comment]
the button is only showing during mouse hover:

bug

can you fix it please? https://www.privacytools.io/#participate

**Comment by AKJT** [comment]
It looks like the `custom.css?v=11` is cached on the server, but other `?v=X` or without works.
https://github.com/privacytoolsIO/privacytools.io/blob/master/index.html#L45

cached
- https://www.privacytools.io/css/custom.css?v=11

works
- https://www.privacytools.io/css/custom.css
- https://www.privacytools.io/css/custom.css?v=0
- https://www.privacytools.io/css/custom.css?v=12

**Comment by Shifterovich** [comment]
I'd also change the background color.

**Comment by privacytoolsIO** [comment]
Thanks mate

**Pull request merged**
