### PR TITLE
Add Pale Moon

### PR DESCRIPTION
**Pull request by gjhklfdsa**
## Description
Add Pale Moon to browser "Worth Mentioning"

## Software Criteria
**Free Software**: Yes, source: https://github.com/MoonchildProductions/UXP/issues/923
**Cross-platform**: Yes, official supports Windows and Linux with community builds for various other OSes.
**Ease of use**: From personal experiences, yes. Very easy to use.
**Privacy respecting**: Yep, I would argue better than vanilla Firefox but, this is a low bar.
**Different**: Technically not in the criteria, but many seem to care about. Pale Moon isn't like Ice Cat or Waterfox which are basically just old-Firefox rebranded. Pale Moon utilizes its own layout engine [Goanna](https://www.wikipedia.org/wiki/Goanna_(software)) with many differences to gecko like single-process mode for security. If you look around you will find a thriving community supporting privacy.

### CODE REVIEW

**Comment by beerisgood** [comment]
No. Pale Moon make you more unique then Firefox.
Also you don't have any improvement against Firefox but opposite like unsigned add-ons, no Webextension add-ons and more.

And yeah, a "own" engine from 1? 2? Guys. Not very secure

**Comment by gjhklfdsa** [comment]
> No. Pale Moon make you more unique then Firefox.

So does Brave and TOR. If I understand correctly, it is still similar enough to evade much fingerprinting.

>  Also you don't have any improvement against Firefox but opposite like unsigned add-ons, no Webextension add-ons and more.

What are you even trying to say? This is all incorrect. Pale Moon  has many extensions[1](https://addons.palemoon.org/extensions/) and you can sign them.

**Comment by beerisgood** [comment]
> So does Brave and TOR. If I understand correctly, Pale Moon is still similar enough to evade much fingerprinting.

Brave yes, Tor no. All Tor browser use (if not modified any stuff) the same signature which provide the only good solution from all browsers. Firefox have some Tor patches but not all features


> What are you even trying to say? This is all incorrect. Pale Moon has many extensions[1](https://addons.palemoon.org/extensions/) and you can sign them. Even for the extensions that might not be signed, you still utilize HTTPS.

I try to say that Pale Moon isn't better choice for privacy AND for security.
Also i don't care that Pale Moon have addons as they are based on old and unsecure Not-WebExtension-base.
And HTTPS have nothing to do with addons.

**Comment by gjhklfdsa** [comment]
> Brave yes, Tor no. All Tor browser use (if not modified any stuff) the same signature which provide the only good solution from all browsers. Firefox have some Tor patches but not all features

TOR, technically is easier to distinguish because of IP (tor exit nodes are public) and extensions + blocking stuff like WebRTC. Not that this doesn't make these improvements.
The TOR team does and continues to evaluate every change with the implications to fingerprinting.

> I try to say that Pale Moon isn't better choice for privacy AND for security.

I'm not saying it is, this is the reason we have a "Worth Mentioning" section.
Generally speaking, these are very different browsers.

> Also i don't care that Pale Moon have addons as they are based on old and unsecure Not-WebExtension-base.

This isn't true. You can find many of the recommended addons like [Decentraleyes](https://addons.palemoon.org/addon/decentraleyes/) and [uBlock Origin](https://github.com/gorhill/uBlock#firefox--firefox-for-android). 

You have to remember, much of Pale Moon isn't from Firefox. They are there separate organization.

**Comment by beerisgood** [comment]
@gjhklfdsa yeah, but old versions of add-ons.
I leave this here. You better read more about crap like Pale Moon and then come back.

**Comment by gjhklfdsa** [comment]
> @gjhklfdsa yeah, but old versions of add-ons.

Not true, these should be actively maintained addons. 

> I leave this here. You better read more about crap like Pale Moon and then come back.

I would love to know the source of your information, perhaps you could point me in the direction?

I would also like to recommend reading this forum post: https://forum.palemoon.org/viewtopic.php?f=4&t=7818

I would also like to point out that to make a good browser, "tons" of extensions is not a requirement. Brave has few with direct support, and TOR recommend you only install a few, as many will harm your privacy. Pale Moon focuses where it counts. ;)

**Comment by Kcchouette** [comment]
Related to #375 
I don't really like that people create a (somewhat forced) PR when discussion is open @Shifterovich :/

**Pull request closed without merging**
