### PR TITLE
browser-tweaks: note privacy.trackingprotection.fingerprinting|cryptomining is FF67+

### PR DESCRIPTION
**Pull request by Mikaela**
Resolves: #1010

### CODE REVIEW

**Comment by Mikaela** [comment]
@Thorin-Oakenpants I could use a review here :)

**Comment by Thorin-Oakenpants** [comment]
I don't have the ability to review anything so you can merge, if that's what you meant, but the changes look good to me :)

**Comment by Mikaela** [comment]
> the changes look good to me :)

This is what I meant, I was afraid there were more notices I was forgetting to add. Thanks


> I don't have the ability to review anything 

I think GitHub would offer you the review buttons in the files tab on top right corner, even if you wouldn't have permission to merge https://github.com/privacytoolsIO/privacytools.io/pull/1012/files

**Comment by Mikaela** [comment]
This is a minor change and there is an approving review, so I am going to merge this.

**Comment by Mikaela** [comment]
```
└┌(%:~/src/github.com/privacytoolsio/privacytools.io)┌- git push origin master
DNS lookup error: data does not exist
Authenticated to github.com ([140.82.118.3]:22).
warning: not sending a push certificate since the receiving end does not support --signed push
Enumerating objects: 28, done.
Counting objects: 100% (26/26), done.
Delta compression using up to 4 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (18/18), 4.67 KiB | 2.33 MiB/s, done.
Total 18 (delta 14), reused 10 (delta 8)
remote: Resolving deltas: 100% (14/14), completed with 8 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.
Transferred: sent 7460, received 3936 bytes, in 2.2 seconds
Bytes per second: sent 3401.5, received 1794.7
To github.com:privacytoolsIO/privacytools.io.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:privacytoolsIO/privacytools.io.git'
```

or maybe not.

**Pull request merged**
