### PR TITLE
Add KeePassXC (KeePassX's community fork)

### PR DESCRIPTION
**Pull request by hugoncosta**
Title, I've also added a little note saying that KeePassX doesn't have regular updates, feel free to use a shorter term to say that, I couldn't remember it. Brought up by #259.

Sidenote: The box is too small for all the text, should we just remove the update comment?

### HTML Preview

http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-3/index.html

### CODE REVIEW

**Comment by kewde** [comment]
Hmm,
The community edition does seem to have a more active development, I don't know what @Shifterovich thinks but replacing it completely might be more interesting route.

**Comment by Shifterovich** [comment]
Wanted to suggest that, but that might require some additional feedback. I know that some people prefer KeePassX over KeePass2 because they don't like mono. But I don't know anything about the community edition.

**Comment by hugoncosta** [comment]
Maybe put the replace the See also with "KeePassXC and KeePassX (older)"?

**Comment by kewde** [comment]
I'm fine with approving this as a temporary measure but how many forks of KeePass are there?

KeePassX?
KeePass2?
KeePassXC?

**Comment by Shifterovich** [comment]
KeePass2 isn't a fork iirc.

**Comment by kewde** [comment]
I suppose we could poll on reddit about this one?
I like the active development of KeePassXC but I hadn't heard of it before and don't know any of the devs..

**Comment by Shifterovich** [comment]
> I like the active development of KeePassXC but I hadn't heard of it before and don't know any of the devs..

Exactly. Non-maintained software is better than ill-maintained software.

**Pull request merged**
