### PR TITLE
Fix icons looking out of place on smaller screens

### LINKED ISSUE #905: 🌐 Website Issue | Icons out of place on mobile devices
## Description
Icons look out of place currently on mobile devices.

## Screenshots
Looks neat:
good

Does not look neat at all:
bad

### PR DESCRIPTION
**Pull request by dawidpotocki**
Fixes #905

### md or bigger screen, but too many icons

don't worry, 2 firefox icons are not in the commit

### CODE REVIEW

**Comment by JonahAragon** [comment]
For some reason I'm not seeing the same "too many icons" view on my browser, I'm only seeing 6 icons on the top row, instead of 7, which affects many more listings.

image

**Comment by dawidpotocki** [comment]
I was able to reproduce it on 90% zoom. It should be fixed now.

**Comment by JonahAragon** [comment]
Still happening to me at any zoom level :/

image

**Comment by dawidpotocki** [comment]
🙄

**Pull request merged**
