### PR TITLE
replace ChatSecure with Conversations.im #76

### PR DESCRIPTION
**Pull request by johnnagro**
#76

> ChatSecure officially dropped support of Android platform and recommends ZomApp or Conversations. So Android should be removed (https://twitter.com/ChatSecure/status/780848326002429953)

### CODE REVIEW

**Comment by pExeen** [comment]
i agree to this proposal

**Comment by BlauerHunger** [comment]
I think ChatSecure should be kept for iOS, but Conversations should be recommended for Android.

**Comment by kewde** [comment]
I've heard several recommendations and praises for Conversations.im so I'm fine with replacing chatsecure.

**Comment by Shifterovich** [comment]
Apparently ChatSecure is in Worth Mentioning now, along with Conversations.im. Should we close @kewde?

**Comment by kewde** [comment]
Hmm, I'd switch Conversations.im with ChatSecure in the worth mentioning. I see that we replaced ChatSecure with Wire.

**Comment by Shifterovich** [comment]
@kewde Better make a new PR?

**Comment by kewde** [comment]
Yeah

**Pull request closed without merging**
