### PR TITLE
Move nav to an include

### PR DESCRIPTION
**Pull request by Vincevrp**
## Description

Resolves: #600 

Move nav to an include so it doesn't show on other pages. Also includes some formatting.

Warning: might conflict with #602 when merging.

### CODE REVIEW

**Comment by Shifterovich** [comment]
On what pages? I put it in the layout so that it's also on the donate page.

**Comment by Vincevrp** [comment]
404 and donate page. It doesn't make sense to have the navbar over there because none of the links will work.

**Comment by Shifterovich** [comment]
I will fix the links.

**Comment by Vincevrp** [comment]
I also prefer the look of the other pages without the navigation bar, it looks out of place.

**Comment by Shifterovich** [comment]
> Move nav to an include so it doesn't show on other pages. Also includes some formatting.

It now does work on other pages. What formatting changes have you made?

**Comment by Shifterovich** [comment]
Oh ok. If you want you can add this to the default.html template. Just don't delete what's there and put the reformatted code there, because I added new functionality. I'm closing this as the navbar does work on other pages now.

**Pull request closed without merging**
