### PR TITLE
Add "URL Shortening Services" Section

### PR DESCRIPTION
**Pull request by asddsaz**
**Description**: Add "URL Shortening Services" Section.
**Why**? Some of the most popular websites like [t.co](https://www.wikipedia.org/wiki/Twitter#URL_shortener), [GA](https://www.wikipedia.org/wiki/Google_Analytics), and [Bit.ly](https://www.wikipedia.org/wiki/Bitly) are all utilized for URL shortening. It is a very useful tool.
**So what are you recommending we add**? 
To Main

- [Ln -S](https://lns.ist)
- [Kutt.it](https://kutt.it/)
- [Elbo](https://elbo.in/)

To Related Information:

- [Matomo](https://matomo.org/)

### CODE REVIEW

**Comment by beerisgood** [comment]
Any URL shortening services are a step backward for security and privacy.
You don't know what behind the link is (if you don't use a addon to reveal this)

Also why are normal links bad?

**Comment by asddsaz** [comment]
> Also why are normal links bad?

They can be long.
I think calling "normal links" bad is an injustice anyway. And agree that it generally can be a privacy issue. But, try putting a "long" link on your business card, it is impractical.

The real issue is that sites like Bit.ly may sell statistics, making this not only a [freedom](https://www.wikipedia.org/wiki/Free_software) issue but also a [security](https://www.wikipedia.org/wiki/Information_security) and [privacy](https://www.wikipedia.org/wiki/Internet_privacy) one.

**Comment by Kcchouette** [comment]
> Ln -S
Kutt.it

For this two, is it open source?
How can we know it's not tracking you? ln -S has no "privacy" section and kutt.it has Secure Connection Failed; An error occurred during a connection to kutt.it. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by asddsaz** [comment]
> For this two, are they open source?

Yes, you can find it [here](https://github.com/PapiCZ/lns) and [here](https://github.com/thedevs-network/kutt).

> ln -S has no "privacy" section

ln -S is minimalist, I wouldn't know if they have a "privacy section". They are fully open-source, they are fully transparent on what they collect. I did however, create an issue for this https://github.com/PapiCZ/lns/issues/2

**Comment by gjhklfdsa** [comment]
@Shifterovich @BurungHantu1605 Why was this PR closed?

**Comment by blacklight447-ptio** [comment]
I wasn't part of the decision, but my guess is that they closed it because url shortening services are kind privacy unfriendly.

**Pull request closed without merging**
