### PR TITLE
remove the old KeePassX completely

### PR DESCRIPTION
**Pull request by quiddity-wp**
After 2.5+ years without change, I suggest removing the old KeePassX completely and slightly expanding the explanation for KeePassXC. Thanks!

### CODE REVIEW

**Comment by Shifterovich** [comment]
Maybe we could go as far as remove KeePass totally and keep only KeePassXC? I've heard from some people that they use KeePassXC because they don't want to use mono to run KeePassX.

**Comment by beerisgood** [comment]
@Shifterovich under Windows the original is still the best

**Comment by Shifterovich** [comment]
In what sense is it better than KeePassXC on Windows? Recommending multiple forks is somewhat confusing. I think we should pick one and recommend only it.

**Comment by beerisgood** [comment]
@Shifterovich There are security differences....

Keepass has Secure Desktop & Two-Channel Auto-Type Obfuscation while KeepassXC doesn't

with Keepass I can create multiple password templates and a default password template for newly generated entries.

Overall I think you have more options and control in Keepass.

**Comment by Shifterovich** [comment]
Okay.

**Pull request merged**
