### PR TITLE
adding protonvpn

### PR DESCRIPTION
**Pull request by facastagnini**
### Description

Our story began at CERN, where the web was born and where our founding team met. In 2014, on the 25th anniversary of the web, we built ProtonMail to make online privacy a reality again for millions of people around the world. The ProtonVPN project was born out of a need to better protect the activists and journalists that use ProtonMail.

In the years since we began as a crowdfunded project, ProtonMail and ProtonVPN continue to be primarily supported by our community and developed with community input. When it comes to fighting for online security and privacy, we have a long track record. Whether it is challenging governments, educating the public, or training journalists, we're committed to staying on the front lines.

We are scientists, engineers, and developers, and we care deeply about the future of the Internet. We're also experts in security and Internet technologies, and we're applying this expertise for the public good. If this sounds like you, we would love to hear from you.

Source: [ProtonVPN's about page](https://protonvpn.com/about)

### HTML Preview

http://htmlpreview.github.io/?https://github.com/fcastagnini/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by CiscoPress** [comment]
your commit looks like an advertisement

> better protect the activists and journalists

what kind of journalists? Can you give me example newspaper names? I don't know government and enterprise critical newspapers in German speaking countries. Most government critical views is anyway comments (forums).

**Comment by Nightfirecat** [comment]
@CiscoPress It wasn't clearly stated, but the comment is a direct lift from [ProtonVPN's about page](https://protonvpn.com/about).

**Comment by facastagnini** [comment]
Thanks @Nightfirecat for linking that, I will add the link in the description.

@CiscoPress I was just lazy about writing something by myself and I thought that the about page got a good summary.

**Comment by Shifterovich** [comment]
Definitely need a lot of feedback on this. One one hand, we don't recommend free VPNs due to reasons stated on the website. On the other hand, ProtonMail is reputable.

**Comment by facastagnini** [comment]
> Definitely need a lot of feedback on this. One one hand, we don't recommend free VPNs due to reasons stated on the website. On the other hand, ProtonMail is reputable.
@Shifterovich that is something that I didnt know how to handle in the PR, they have a free tier, but also several paid plans, more info in their [pricing page](https://protonvpn.com/pricing)
Should I change the PR from free to $8/month?

I feel that I begin this PR with the wrong foot, I am sorry if the description was inadequate. I am not affiliated in any way with the proton people. Has you said, ProtonMail is reputable and I thought that a sister company offering a VPN in the same location offering good features was worth to mention.

**Comment by craftyguy** [comment]
@Shifterovich 

I'm in favor of not listing **any** VPN services on the site, and instead linking to that one privacy site, where users can filter based on their own preferences. It's sketchy choosing to endorse some VPN services and not others, especially given how some of them are on annoying advertising crusades in some public forums. Case in point, this PR definitely reads like an advertisement.

**Comment by Josexv1** [comment]
+1 to @craftyguy almost every VPN if not every save logs in http or vpn traffic, they to this in order to fix issues with their platform, for example i was about to PR this VPN service: http://cloakvpn.com/ running by a reputable member of the Monero community, which doesn't save any kind of logs, but since we don't run the VPN service, it can be a weak point to privacy to the users.

**Comment by Shifterovich** [comment]
Let's not make exceptions for free VPNs. We'll probably replace the entire VPN section with criteria recommendations soon.

**Comment by privacytoolsIO** [comment]
@Shifterovich ProtonVPN is not an exclusive free VPN provider. Have you seen the pricing page? https://protonvpn.com/pricing

**Comment by privacytoolsIO** [comment]
The main issue i see with ProtonVPN is that you can't sign up for a pro account with Bitcoin. Only credit cards and PayPal are supported.

**Comment by Shifterovich** [comment]
I agree that with paid plans, the "If you're not paying for it, you're the product" rule diminishes, but indeed, it doesn't match the criteria fully. I suggest not adding it just yet, as it's a new service, and revisit this issue  later.

**Comment by privacytoolsIO** [comment]
Agreed.

**Comment by Rafficer** [comment]
[Actually they do support bitcoin. And even cash.](https://protonmail.com/support/knowledge-base/paying-with-bitcoin/). Yes I know this is a link for protonmail, but it works exactly the same, as it is the same company and the same team. And as the link states they also accept payments in cash, which is even more untracable than bitcoin.

And generally I agree with the opinion not to use free VPNs, however ProtonVPN is a bit different. Normal free VPNs either sell their data or limit their users with bandwidth or download capacity, which requires logging, doesn't it?

On the other hand ProtonVPN doesn't do anything of it, even for the free accounts. The free accounts are just limited in the server choices and the [bandwidth is limited by the simple fact that those server are super crowded.](https://protonvpn.com/support/increase-vpn-speeds/)

I just wanted to mention this because it looks like that ProtonVPN got declined because of false claims, imho.

**Comment by emanresusername** [comment]
[official comment from proton mail](https://www.reddit.com/r/ProtonVPN/comments/6szuj1/anybody_from_the_proton_team_want_to_chime_in_here/dlhbgd5/)

**Comment by craftyguy** [comment]
As I stated earlier, I highly suggest staying agnostic to VPN services and not recommend *any* specific service. Instead, provide a list of recommendations that folks should look out for, point them to 'that one vpn guy's" vpn list, and let folks decide for themselves.

Discussing whether protonvpn is sketchy or not in their business model is a red herring. Despite their "official statements", and at the end of the day you still have to trust them and thus will never be an option at the end of the day for some folks. By playing favorites, privacytools.io loses some credibility with these folks if, for instance, you recommended this service over others. The same could be said for existing VPN service recommendations. Anyways, that's my $0.02.

**Comment by Shifterovich** [comment]
> 'that one vpn guy's" vpn list, and let folks decide for themselves.

That list lacks a lot of important information and is biased by the author's personal opinions.

**Comment by strypey** [comment]
This discussion seems to have segued from whether or not to add ProtonVPN to the exist list to a more general discussion of the VPN page, which FYI has it's own issue (#559)

**Pull request merged**
