### PR TITLE
Replace broken link

### PR DESCRIPTION
**Pull request by Booteille**
Replace broken link for Block Cloudflare MITM Attack Addon

## Description

Resolves: #442

### CODE REVIEW

**Comment by Vincevrp** [comment]
Can someone confirm that this is still the same extension? I can't seem to find the source.

**Comment by Shifterovich** [comment]
I was thinking the same, hence the review request.

**Comment by whynotrespond** [comment]
@Vincevrp @Shifterovich Why you two didn't respond to my email?

https://notabug.org/themusicgod1/cloudflare-tor/src/master/bcma

**Comment by Shifterovich** [comment]
Sorry, I saw the email but didn't have time to read it and I forgot about it. I'm busy with personal projects lately. 

@Vincevrp do you have time to look into it?

**Comment by Vincevrp** [comment]
There's no reference to the source code from the link provided in the PR, nor vise versa. The addon only has some Russian text on the page, which makes it a bit sketchy.

> Sorry, I saw the email but didn't have time to read it and I forgot about it. I'm busy with personal projects lately.
> 
> @Vincevrp do you have time to look into it?

Same, sorry.

**Comment by Vincevrp** [comment]
So I received another email about this. I've changed the link to the project instead of the AMO page because:

Quote from the email:

> Our collaborator who have access to AMO gone AWOL

Also

> P.S Say hi to @Booteille for us as we cannot deal with GitHub.

**Comment by Booteille** [comment]
Thanks for your investigation, all of you!

**Pull request merged**
