### PR TITLE
Add crypt.ee

### LINKED ISSUE #502: Consider adding Cryptee
Hey team 👋🏻 

Maker of [Cryptee](https://crypt.ee) here.
[I've launched Cryptee on privacy tools' reddit about a month ago](https://www.reddit.com/r/privacytoolsIO/comments/8t1oqz/a_new_privacy_tool_ive_been_building_for_15_years/), 
with a pretty sweet response rate of [top 15th post](https://www.reddit.com/r/privacytoolsIO/top/?t=year) of this year under r/privacytoolsIO.

Is it possible to add Cryptee under Notes / Docs / Photos ?
I can happily answer any outstanding question or doubt there may be. 
Would love for Cryptee to reach the broader community.

All the very best from Northern Europe,
J

### PR DESCRIPTION
**Pull request by Avizini**
## Description
Adding crypt.ee to worth mentioning section. Resolves #502 

### HTML Preview

http://htmlpreview.github.io/?https://github.com/Avizini/privacytools.io/blob/add-crypt/index.html

### CODE REVIEW

**Comment by Avizini** [comment]
@Shifterovich I created a new branch add-crypt and then created this PR directly to privacytoolsio master branch but over here it has included my commit for tutanota also and it says I need to resolve some conflicts. What should I do now?

**Comment by Shifterovich** [comment]
The new branch is based on your master branch. I'll fix it for you (I'll just remove the tutanota stuff).

**Comment by Shifterovich** [comment]
Hm, seems like the conflict is more than just the tutanota stuff. Likely your master is very outdated. Unless someone can suggest a better approach I'd just delete the repo, fork it again, create this PR again and open the Tutanota PR once they support BTC for payments.

**Comment by Avizini** [comment]
No wait, let me try it first.

**Comment by Avizini** [comment]
@Shifterovich I'll close this and create a new one after deleting my repository.

**Pull request closed without merging**
