### PR TITLE
Create WARRANTY

### PR DESCRIPTION
**Pull request by asddsaz**
Add WARRANTY.txt

As listed here: http://www.wtfpl.net/faq/

### CODE REVIEW

**Comment by Shifterovich** [comment]
Warranty notice is usually included in the license text.

**Comment by JonahAragon** [comment]
I'm not sure if this is necessary since this is documentation, not source code? Nobody is "running" this on their own machines.

I'd rather see a license change to CC0 if anything.

**Comment by Mikaela** [comment]
> I'd rather see a license change to CC0 if anything.

WTFPL is compatible and would let us perform relicensing to CC0, wouldn't it?

**Comment by asddsaz** [comment]
@Shifterovich It shouldn't matter where you put the warranty.

**Comment by Shifterovich** [comment]
> It shouldn't matter where you put the warranty.

So if it's in the license, why open this PR?

**Comment by JonahAragon** [comment]
@Mikaela it is possible but I don’t know if something like #884 would cause us any issues. 

@Shifterovich I don’t think it is in the WTFPL is it? The license is pretty bare.

**Comment by Shifterovich** [comment]
WTFPL is a shitty license. We should use an actual license like MIT or preferably CC0.

**Comment by gjhklfdsa** [comment]
@Shifterovich As I understand it, warranty can be put anywhere is a source code file and still be valid.

**Pull request closed without merging**
