### PR TITLE
Change Tor icon

### PR DESCRIPTION
**Pull request by EvasivePangolin**
### Description
Replace the circular Tor icon with a rounded square icon, to make it match the theme better. 
Idea and rounded icon is from @victorhck issue #441 

### HTML Preview
https://htmlpreview.github.io/?https://github.com/evasivepangolin/privacytools.io/blob/change-tor-icon/index.html

### CODE REVIEW

**Comment by EvasivePangolin** [comment]
It does look a bit weird under "Privacy-Conscious Email Providers - No Affiliates" (the normal url icon is round). Could do an edit to use a the round icon in the lists, and the rounded-square for things like the Browser Recommendations section

**Comment by victorhck** [comment]
I also made a rounded square icon for url icon, you can check it out here:
https://victorhck.gitlab.io/privacytools-es/img/layout/www.png

**Comment by EvasivePangolin** [comment]
Added a commit to change the circular www.png icon to @victorhck's rounded square version.

**Comment by EvasivePangolin** [comment]
Thanks @victorhck :)

**Comment by kewde** [comment]
Thanks, looks better indeed :+1:

**Comment by victorhck** [comment]
a pleasure! :)

**Pull request merged**
