### PR TITLE
Switch Red/Green in KDL section

### LINKED ISSUE #333: Red and Green box position switch in Key disclosure law
In "Key disclosure law" the green box is to the right instead of the left. In all other cases the green (best option) is the left.

Solution: red and green box switch position.

### PR DESCRIPTION
**Pull request by shifterovich2**
### Description

**Don't merge until the design is resolved.**

Resolves #333 

Not sure whether I like it more now. Maybe use the same layout as #ukusa?

### HTML Preview

http://htmlpreview.github.io/?https://github.com/shifterovich2/privacytools.io/blob/switch-red-green-kdl/index.html

### CODE REVIEW

**Comment by kewde** [comment]
@Shifterovich 
Is @shifterovich2 an account that you own?

**Comment by kewde** [comment]
Special key disclosure laws exist for Belgian citizens. I've moved it to the right section.

**Comment by Shifterovich** [comment]
Yes, it's the account I use on public/school computers.

**Comment by shifterovich2** [comment]
@kewde What do you think about the layout? Use the same as #ukusa or keep it like this?

**Comment by Shifterovich** [comment]
@hugoncosta Your opinion on the layout?

**Comment by hugoncosta** [comment]
The preview says it cannot load, could you give me another link?

**Comment by Shifterovich** [comment]
Right, I apparently deleted the branch. I'll update the link once I have time to upload the files to my website.

**Comment by hugoncosta** [comment]
btw I was thinking, I don't believe we should change the layout. We use this on the number eyes section too, and we have the worst offenders first. I believe that the current layout should stay, since both KDL and #Eyes are warnings and not necessarily tools/advices. Our philosophy of putting the "best" option with a green box and to the left should remain, by putting the "worst" offenders (in this case) to the left and in a red box.

**Comment by Shifterovich** [comment]
@kewde?

**Comment by kewde** [comment]
@Shifterovich the link is dead so I can't see it anymore. Can you snap a pic of it?

**Comment by Shifterovich** [comment]
https://htmlpreview.github.io/?https://raw.githubusercontent.com/privacytoolsIO/privacytools.io/89ce79e4637bc8349f091bbc5e538feafbb1384e/index.html#kdl

**Comment by hugoncosta** [comment]
I'm still not conviced. I believe that the panel on the left should be the most important - either the "stay away" or "you should really use this". If we change the KDL from "Good" to "Bad", we should also change the Global Mass Surveillance and put the Fourteen Eyes first (switch like in here).

**Comment by Shifterovich** [comment]
Agree, I think I liked it better before aesthetically as well. Just wanted to know what you think. @kewde @beardog108 what do you think? Merge or close?

**Comment by kewde** [comment]
I don't really care about this change, it's just moving boxes :package: and the order of worst -> best is clear here.

**Pull request closed without merging**
