### PR TITLE
Added ScriptSafe to Firefox Privacy Add-ons

### PR DESCRIPTION
**Pull request by asuh**
Added ScriptSafe Add-on to list of Excellent Firefox Privacy Add-ons. It's open source, regularly maintained and gives NoScript a run for its money.

http://htmlpreview.github.io/?https://github.com/asuh/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by hugoncosta** [comment]
From what I can see, it doesn't appear to be much different than NoScript. What are the main differences?

**Comment by asuh** [comment]
Aside from the UI, ScriptSafe has an options page that contains a lot of controls that NoScript doesn't, such as fingerprinting blocking. So while they do accomplish similar blocking, ScriptSafe offers different ways to do this and additional nuanced control in the Options.

**Comment by beerisgood** [comment]
@asuh what fingerprint blocking exactly?

**Comment by asuh** [comment]
@beerisgood I've attached a screenshot of the long list of fingerprinting that can be blocked. He's tried to include a lot, some of which is buggy from my usage but still a very nice feature to include.
scriptsafe-fingerprinting

**Comment by asdfghjz** [comment]
Sounds very interesting...have you considered asking about this in the Reddit?

@asuh

**Comment by asuh** [comment]
I linked to it on the subreddit a few years ago with little response. I figured I should just create a pull request instead.

**Comment by Shifterovich** [comment]
@kewde @beerisgood @Atavic @Hillside502 thoughts? Looks good to me

**Comment by Atavic** [comment]
:+1: Installed some moons ago, I then switched to [this other webextension](https://gbaptista.github.io/luminous/doc/en-US/) that is similar.

**Comment by Shifterovich** [comment]
@asuh Can you resolve the conflicts?

**Comment by asuh** [comment]
@Shifterovich  Merged upstream. Let me know if something isn't right

**Comment by Shifterovich** [comment]
@Atavic Why did you switch?

**Comment by Atavic** [comment]
Because I find Luminous interesting, it has some unique feats, like blocking specific *javacript events* like *beforeunload* or *mousemove* that can be used maliciously for loading pop-ups or opening another page on a new window. If you ever used some free hosting site, you probably know some of these issues, like when a new windows pops up and the focus is forced on that new window: luminous can also block these [Focus Events](https://github.com/gbaptista/luminous/blob/master/doc/en-US/guides/how-it-works/what-is-detected.md#common). I like both Scriptsafe and Luminous and I experiment with the latter sometimes.

**Pull request closed without merging**
