### PR TITLE
search-engines: add Mojeek to worth mentioning

### PR DESCRIPTION
**Pull request by Mikaela**
Resolves: #982

### CODE REVIEW

**Comment by JonahAragon** [comment]
> The only ~~possible~~ **listed** exception is stating that their are no viable alternatives.

Seems like a fair arguement for a worth mentioning inclusion: https://github.com/privacytoolsIO/privacytools.io/issues/982#issuecomment-500601057

**Comment by Mikaela** [comment]
@privacytoolsIO/editorial What do you think about the two NACKs?

**Comment by Mikaela** [comment]
I think I am going to wait for @privacytoolsIO/editorial here.

**Comment by erciccione** [comment]
So, this got merged beside the 2 nacks with no explanation/further discussion? One member jumps in and merge a PR without addressing the concerns or give any sort of explanation?

I hope this is not the normal workflow of privacytools...

**Pull request merged**
