### PR TITLE
Improvements to readme

### PR DESCRIPTION
**Pull request by alexbooker**
**Changes**

- Took the text from [this issue](https://github.com/privacytoolsIO/privacytools.io/issues/1) and put it in the readme.md. It is much more prominent now.
- I made the contributing guidelines in readme.md a little bit clearer with a header, bullet points and an additional example link.
- I made the warning about not submitting ideas here on GitHub friendlier so that people feel more welcome to join the discussion on Reddit.
- Added a contributing.md file. Now, when users submit an issue, they will see an alert like this:
 

The link will take them to contributing.md. (If you want, you can [disable issues](https://help.github.com/articles/disabling-issues/), by the way.)
- Corrected the capitalization in the tagline, in readme.md. You may want to do this for the repository description, also.
- Added "support us" section to readme.md.
- Used logo in place of header. It adds some brand identity to the repository and looks good, too.

You can see the outcome on my fork, [here](https://github.com/alexbooker/privacytools.io).

**Note**

I apologize for not asking permission to submit a pull request first. I _hope_ you like the changes that I made but if not, I will understand if you would rather not merge them. 

I intentionally made a lot of small commits so that you can [cherry pick](http://git-scm.com/docs/git-cherry-pick) the ones that you want (if any). 

Thanks.

### CODE REVIEW

**Comment by alexbooker** [comment]
Anything else I can do for this PR?

**Comment by privacytoolsIO** [comment]
Thank you so much, alexbooker. Good work. I could use some help maintaining this project on github. Would you be interested?

**Comment by alexbooker** [comment]
Yes, I would -- I love the website :smile:

**Comment by privacytoolsIO** [comment]
I've just added you as a collaborator. Will that enhance your rights in this repository?

**Comment by alexbooker** [comment]
Yep. 

I was also subscribed to any notifications relating to this repository. 

If I see any issues or pull requests, I will be sure to weigh in on them.

Am I speaking to [u/BurungHantu](https://www.reddit.com/user/), by the way?

**Comment by privacytoolsIO** [comment]
Yes, that's me. Are you also on reddit?

**Comment by alexbooker** [comment]
Yep. I'm [u/bookerio](https://www.reddit.com/user/bookerio/).

**Pull request merged**
