### PR TITLE
Replace Tor image button with proper font icon

### PR DESCRIPTION
**Pull request by dawidpotocki**
Who thought that it was a good idea?

### CODE REVIEW

**Comment by dawidpotocki** [comment]
> kind of a weird icon, I'd probably prefer a more stylized one like in
> their browser since it'd look better as a font. but whatever, lgtm

Well, I'm just using the official one :P.
https://styleguide.torproject.org/visuals/#assets

**Comment by JonahAragon** [comment]
yeah, yeah, just doesn't look great as a button imo. seems like very thin lines.

**Comment by djoate** [comment]
Missing Tor icon at https://www.privacytools.io/providers/email/

**Comment by dawidpotocki** [comment]
> Missing Tor icon at https://www.privacytools.io/providers/email/

I know it's a case. Will fix it soon™.

**Pull request merged**
