### PR TITLE
Restore BitWarden

### PR DESCRIPTION
**Pull request by Shifterovich**
Reverts privacytoolsIO/privacytools.io#720

https://github.com/privacytoolsIO/privacytools.io/issues/719#issuecomment-454454146

@kspearrin ping

### CODE REVIEW

**Comment by Shifterovich** [comment]
If we don't have any reason to keep BitWarden removed, I'll merge this.

**Comment by kspearrin** [comment]
@Shifterovich The updates should be live in the next few days.

**Comment by Shifterovich** [comment]
Can you ping me w/ links when they're live?

**Comment by Shifterovich** [comment]
As the issue mentions: https://github.com/privacytoolsIO/privacytools.io/issues/719#issuecomment-454454146

**Comment by kspearrin** [comment]
@Shifterovich Just as an update here. v2.9.0 of the web vault is live as well as 1.38.0 of the browser extension. v1.22 of the mobile app is currently in the beta track on the play store and v1.13 of the desktop app should be released soon.

**Comment by kspearrin** [comment]
@Shifterovich Mobile app v1.22 on iOS and Android has now been released to production with these changes as we;;. Should be good to go now.

**Pull request merged**
