### PR TITLE
Update Signal logo and entries w/ APK link

### PR DESCRIPTION
**Pull request by NinebitX**
### Description

I updated the Signal logo. The titles and descriptions in the Signal entries were inconsistent with each other. It's also cleaner and more consistent with the other entries to only display one download link. I added a link to the Signal APK download site to the Related Information sections, because PrivacytoolsIO recommends operating systems that don't include Google Play, and the Signal APK download site isn't linked to directly from the signal.org front page.

### HTML Preview

http://htmlpreview.github.io/?https://github.com/NinebitX/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by NinebitX** [comment]
@kewde Would it be better to say: "The app provides one-to-one and group messaging, as well as voice and video calling. All communications are end-to-end encrypted."

**Comment by kewde** [comment]
I'm not really fond of the word one-to-one, but I won't be blocking a merge proposal if you decide to use it anyways. 
Here's my attempt at fixing the sentence that still clearly underlines that all of the following communication method are secure.
"The app provides end-to-end encrypted communication such messaging, group conversations, voice and video calls. "

**Comment by NinebitX** [comment]
@kewde How about simply saying: "The app provides instant messaging, as well as voice and video calling. All communications are end-to-end encrypted." 

I'm sure people can figure out that it also provides other features like group messaging by visiting the Signal website.

**Comment by kewde** [comment]
@NinebitX :+1:

**Pull request merged**
