### PR TITLE
Mention that Wire stores metadata

### PR DESCRIPTION
**Pull request by NinebitX**
### Description

Added links to a Motherboard article to the Related Information sections under Encrypted Instant Messengers and  Encrypted Video & Voice. Adding a disclaimer was also proposed by [a user on Reddit](https://www.reddit.com/r/privacytoolsIO/comments/6auj04/secure_messaging_app_wire_stores_everyone_youve/dhhldfw/?context=3
): "I'd just put a disclaimer ln the site. It really depends on your threat model, but I do think that Wire should find a way to encrypt that data."

I also made some minor aesthetic improvements, like indenting the line about ChatSecure and removing an unnecessary link from Wire's description.

### HTML Preview

http://htmlpreview.github.io/?https://github.com/NinebitX/privacytools.io/blob/patch-1/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
Maybe add that to the Wire description?

**Comment by NinebitX** [comment]
I can add the following to the description:

>Caution: The company keeps a list of all the users you contact until you delete your account.

**Comment by Shifterovich** [comment]
I'd put that on a new line. Maybe just add a <br>?
I'd do the change myself, but I'm busy with other projects, sorry.
Update it and I'll merge.

**Comment by NinebitX** [comment]
`<br>` added. Do we wait for a review from @kewde?

**Pull request merged**
