### PR TITLE
Updating the Tor binary included with Ricochet

### PR DESCRIPTION
**Pull request by tya99**
## Description

Screenshot: ricochet-symlinks

Resolves:  #474

### CODE REVIEW

**Comment by Shifterovich** [comment]
Preview: http://62.102.148.154:19472/

**Comment by Shifterovich** [comment]
@beardog108 Thoughts?

**Comment by beardog108** [comment]
@tya99 I think it would be better if the ricochet warning was collapsible or linked to a github comment (like how we do the ipfs warning), because it takes up too much screen real estate just for people who want to use ricochet

**Comment by Vincevrp** [comment]
> @tya99 I think it would be better if the ricochet warning was collapsible or linked to a github comment (like how we do the ipfs warning), because it takes up too much screen real estate just for people who want to use ricochet

I agree.

**Comment by Shifterovich** [comment]
Books often have sections with info like this at the end. Maybe we could create a separate page for these things?

**Comment by beardog108** [comment]
@Shifterovich If we still have a link that would jump/go to the section, that would be acceptable.

**Comment by Shifterovich** [comment]
If we move this section to the bottom of the page, the links will work.

**Comment by tya99** [comment]
This depends on https://github.com/privacytoolsIO/privacytools.io/issues/746

**Comment by BurungHantu1605** [comment]
We'll figure something out soon.

**Comment by BurungHantu1605** [comment]
Done. Thanks @tya99

**Pull request closed without merging**
