### PR TITLE
add Firefox about_config values for Referer

### PR DESCRIPTION
**Pull request by groovecoder**
### Description
Add suggested values for `network.http.referer.XOriginPolicy` and `network.http.referer.XOriginTrimmingPolicy`

### HTML Preview

http://htmlpreview.github.io/?https://github.com/groovecoder/privacytools.io/blob/about-config-referer/index.html

### CODE REVIEW

**Comment by kewde** [comment]
I wasn't aware about these configuration settings, thanks!

**Comment by kewde** [comment]
Is there a particular reason why you set `network.http.referer.XOriginPolicy` to 1 instead of 2?

1: a.example.com and b.example.com would be allowed
2: only b.example.com & b.example.com would be allowed

Seems like the second option is even more secure, but maybe at the expense of functionality.

**Comment by groovecoder** [comment]
Right; `1` would seem to break fewer things. When we studied its effect on user-reported breakage, it seemed to be minimal. We didn't study `2` yet, but we probably will. I'll update here again if `2` seems just as good.

**Comment by groovecoder** [comment]
Sorry I had my settings crossed. We didn't actually study `XOriginPolicy` effects on breakage. But the assumption is the same - referers to eTLD will presumably break fewer sites.

**Comment by Shifterovich** [comment]
Not sure whether `1` really helps. Maybe recommend `2` and explain that if it breaks sites a lot, the user should try changing it to `1`?

**Comment by groovecoder** [comment]
Depends on the adversary and the risk. eTLD's would able to combine/track across the sub-domains if they wanted to. But I see the other privacy settings tweaks maximize privacy, so `2` makes sense here.

Updated commit to suggest `2` and also to suggest a global `Referer` trimming policy.

**Pull request merged**
