### PR TITLE
Add 2FA Column to Email Providers section

### PR DESCRIPTION
**Pull request by adalricus**
## Description

Resolves: #144  

#### Check List

- [X] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

* Netlify preview for the mainly edited page: https://deploy-preview-1670--privacytools-io.netlify.com/providers/email/

### CODE REVIEW

**Comment by dngray** [comment]
Lets not merge this yet, I am working on a new email section which will have this.

**Comment by nitrohorse** [comment]
Nice, thanks for the PR @adalricus 👍🏼 This info will be good to have for the Email section.

**Comment by dngray** [comment]
All of the providers support 2FA so there's not much point in this.

Additionally the one marked that does not, apparently does https://howto.disroot.org/en/tutorials/cloud/introduction#two-factor-authentication

**Comment by adalricus** [comment]
Daniel Nathan Gray @ 2020-01-30 11:51 IST:

> Additionally the one marked that does not, apparently does https://howto.disroot.org/en/tutorials/cloud/introduction#two-factor-authentication

Disroot doesn't support 2FA for emails, that link points to their
nextcloud manual.

**Pull request closed without merging**
