### PR TITLE
Remove Signal until Removal of Proprietary Software

### PR DESCRIPTION
**Pull request by ghbjklhv**
**Description**: Signal uses non-free software. I would like to push the notion to remove them until all non-free dependencies have been resolved.

> "[Signal] currently has a proprietary dependency on Google libraries. Helping the project remove this dependency and operate the necessary infrastructure is a high priority. " - [FSF](https://www.fsf.org/campaigns/priority-projects/voicevideochat)

### CODE REVIEW

**Comment by angela-d** [comment]
Another days' old account requesting removal of one of the (arguably) most private chat apps.

My tinfoil hat is tingling.

If this was a legit user that just got into privacy, why not post the concern on Signal's repo?  Asking a *guide site* to flat out remove it '**until..**' is highly suspect.

Why not request a warning or badge to communicate the concerns?  Why flat out **remove it**?

**Comment by ghbjklhv** [comment]
> I don't think this is a good idea as Signal is currently possibly the easiest E2EE messaging solution.
> 
> I am selecting "Request changes", because there is no "Disapprove" button.

I understand that this seems to be a popular narrative. 
But I must say that clients RetroShare are just as easy and arguably more private. 



> Another days' old account requesting removal of one of the (arguably) most private chat apps.
> 
> My tinfoil hat is tingling.
> 
> If this was a legit user that just got into privacy, why not post the concern on Signal's repo? Asking a _guide site_ to flat out remove it '**until..**' is highly suspect.
> 
> Why not request a warning or badge to communicate the concerns? Why flat out **remove it**?

My account it fairly new because I support free software and don't generally use Github.

**Comment by blacklight447-ptio** [comment]
As far as I know, privacytools.io does not have any strict open source requirement, so does not have to be removed because of that. Also, Signal is open source and fully reproduciable if you use the apk version, sure it may has google in the google play version, but at that point your already running google play anyway, which makes it pointless. I would vote to reject this pull request.

**Comment by JonahAragon** [comment]
privacytools.io does not have a free software requirement. We are recommending the best *overall* tools in each respective category. To discuss the removal of Signal lets stick to the open discussion issue #779. Closing this PR unless that issue is resolved first or @privacytoolsIO/editorial disagrees.

**Comment by ghbjklhv** [comment]
@JonahAragon Privacy tools.io although does not have a free software requirement, 
it does have an open source one.

Exemptions are supposed to only be made when it is considered impossible to find a product that fits all criteria.

**Comment by blacklight447-ptio** [comment]
> @JonahAragon Privacy tools.io although does not have a free software requirement,
> it does have an open source one.
> 
> Exemptions are supposed to only be made when it is considered impossible to find a product that fits all criteria.

AS jonah and I are both privacytools.io team members, we are not aware of us having ever stated that we have a open source only policy. It is a preference, but not a requirement. But if you really think we have such a policy stated somewhere, i would like to have a link to the place where it is stated.

**Pull request closed without merging**
