### PR TITLE
Joining CanvasBlocker to the Add-Ons List 

### PR DESCRIPTION
**Pull request by hugoncosta**
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1786

## Description

Currently, CanvasBlocker is discretly mentioned under Browser Fingerprinting. Since it's a plugin like all the others, I believe it should join the Add-Ons. The order is indifferent, I put it in the middle. #1786 

#### Check List 

- [X] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [X] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [X] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-1787--privacytools-io.netlify.com/

* Code repository of the project (if applicable): https://github.com/hugoncosta/privacytools.io

### CODE REVIEW

**Comment by Mikaela** [comment]
> Netlify preview for the mainly edited page: https://deploy-preview-1787--privacytools-io.netlify.com/

This means the page you mostly edited which is in this case https://deploy-preview-1787--privacytools-io.netlify.com/browsers/#addons

> Code repository of the project (if applicable): https://github.com/hugoncosta/privacytools.io

This means the project you edited which means Canvas Blocker, but I would also accept unapplicable if it was already listed even if as a worth mentioning.

I cannot review at the moment (see my GitHub status).

**Comment by dngray** [comment]
This is not a good idea if you use `privacy.resistFingerprinting = true`.

We [should include a warning](https://github.com/ghacksuserjs/ghacks-user.js/issues/767#issuecomment-515738986) regarding that.

**Comment by dngray** [comment]
We could add this as an advanced addon as @Thorin-Oakenpants suggests https://github.com/privacytoolsIO/privacytools.io/issues/1877#issuecomment-623786468

**Comment by dngray** [comment]
I'm thinking we could list this under advanced, paired with uMatrix as suggested https://github.com/privacytoolsIO/privacytools.io/issues/1877#issuecomment-623786468

I eventually want to move Cookie Autodelete out of there into another group "cookie management" or something like that and mention Containers/Temporary Containers as that's a better approach.

**Pull request merged**
