### PR TITLE
Change Etherpad URL to Etherpad.net

### PR DESCRIPTION
**Pull request by gjhklfdsa**
**Description**: Change Etherpad URL to [Etherpad.net](https://etherpad.net)
**Why**? Ease of use, Etherpad.net is plug-n-play while Etherpad is hard to set up.

### CODE REVIEW

**Comment by Shifterovich** [comment]
> Ease of use, Etherpad.net is plug-n-play while Etherpad is hard to set up.

We should recommend both then. Etherpad as the main recommendation and a mention to Etherpad.net in the description perhaps?

**Comment by gjhklfdsa** [comment]
> > Ease of use, Etherpad.net is plug-n-play while Etherpad is hard to set up.
> 
> We should recommend both then. Etherpad as the main recommendation and a mention to Etherpad.net in the description perhaps?

Ok, done.

**Comment by gjhklfdsa** [comment]
> > Ease of use, Etherpad.net is plug-n-play while Etherpad is hard to set up.
> 
> We should recommend both then. Etherpad as the main recommendation and a mention to Etherpad.net in the description perhaps?

@Shifterovich Ok, done.

**Comment by Kcchouette** [comment]
be careful: it's not "change" but "add"
And moreover, we should instead propose https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad as if you want to find a third-party instance instead of force-proposed etherpad.net who seems to not be an official instance of developpers

**Pull request closed without merging**
