### PR TITLE
Add DuckDuckGo to worthwhile mentions

### PR DESCRIPTION
**Pull request by Devices**
I thought DDG would fit in the same list as other privacy focused search engines. Their privacy policy is simple enough for anyone to understand, but they are clear in the workings of the search engines.

https://duckduckgo.com/privacy

### CODE REVIEW

**Comment by bakku** [comment]
Related to this thread https://github.com/privacytoolsIO/privacytools.io/issues/84.

I would agree to put it to the mentions section.

**Comment by Devices** [comment]
I tried to make an unrelated change and it pushed it to this pull request as well and I see no way to undo that.

**Comment by e5f3c2ea895af0f27667** [comment]
You should also mention their onion service: https://3g2upl4pq6kufc4m.onion

**Comment by privacytoolsIO** [comment]
#84

**Pull request merged**
