### PR TITLE
add magic-wormhole to the file sharing section

### PR DESCRIPTION
**Pull request by emanresusername**
### Description

add [magic-wormhole](https://github.com/warner/magic-wormhole) to the file sharing section

for #357 

just copied the description from the github page (might be a little long?)

took (and resized) the picture from the [slides pdf](http://www.lothar.com/~warner/MagicWormhole-PyCon2016.pdf)

wasn't sure on os, it explicitly mentions [osx](https://github.com/warner/magic-wormhole#os-x), [linux](https://github.com/warner/magic-wormhole#linux) and [windows](https://github.com/warner/magic-wormhole#windows), but i'd imagine you could get it on android or ios (jailbroken) if python's there :thinking: 

### HTML Preview

http://htmlpreview.github.io/?https://github.com/emanresusername/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
Maybe I'd remove the link to the PyCon resources. Also, not sure whether HTML5 doesn't break some things to some degree.

**Comment by emanresusername** [comment]
removed pycon :+1: 
didn't add any new html5 features, intentionally anyway, mainly just copied and tweaked the `div.col-sm-4` elem from onionshare?

**Comment by Shifterovich** [comment]
Ah, well for some reason GitHub shows that line as modified. screenshot-2017-11-11 add magic-wormhole to the file sharing section by emanresusername pull request 359 privacytoolsi

Anyway, I'll wait for an approval and then merge (if we can't get an approval in the next few days, I'll merge anyway). @kewde

**Comment by emanresusername** [comment]
oh :astonished: 
must be an autosave/cleanup hook i wasn't paying attention to
i can remove that and squash everything down into 1 commit if you like?

**Comment by Omar-Elrefaei** [comment]
Yeah this is an amazing tool

**Pull request merged**
