### PR TITLE
add partial centralization warning for Jami

### PR DESCRIPTION
**Pull request by lrq3000**
#### Description

Resolves: #1727 

Changes:
* Add label warning that Jami is partially centralized
* Extend description to mention all communications are end-to-end encrypted, including through TURN servers if used.

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-1752--privacytools-io.netlify.com/software/real-time-communication/#peer-to-peer

### CODE REVIEW

**Comment by lrq3000** [comment]
Sorry I didn't know the syntax for links in a label, now it's fixed :-)

**Comment by blacklight447-ptio** [comment]
The preview looks great so far, ill leave a review tommorow!

**Comment by lrq3000** [comment]
@Mikaela do you mean something like [this](https://jami.net/why-is-jami-truly-distributed/)? This is linked by the first reply in the [issue](https://git.jami.net/savoirfairelinux/ring-project/issues/765) I linked in the warning, so from the issue, the user can easily go there. I chose the issue because it's a lot less verbose and it specifically addresses how to workaround this issue (ie, how to self-host), whereas the blog post while being maybe cleaner only describe the issue without providing any solution.

**Comment by lrq3000** [comment]
Also I just noticed they say in the blog post that:

> Furthermore, the data that users choose to share is always transmitted through entirely peer-to-peer connections, except when a TURN server is necessary. Even then, it is fully end-to-end encrypted and never stored elsewhere than on the end-users’ devices.

Maybe we should add that in the description (that it's always end-to-end encrypted)?

**Comment by blacklight447-ptio** [comment]
> 
> 
> Also I just noticed they say in the blog post that:
> 
> > Furthermore, the data that users choose to share is always transmitted through entirely peer-to-peer connections, except when a TURN server is necessary. Even then, it is fully end-to-end encrypted and never stored elsewhere than on the end-users’ devices.
> 
> Maybe we should add that in the description (that it's always end-to-end encrypted)?

Seems like a good idea to me.

**Comment by Mikaela** [comment]
Would it be possible to say in the warning what exactly is not decentralized?

**Comment by lrq3000** [comment]
@Mikaela Here is the list:

* push notifications
* the OpenDHT proxy
* bootstrap
* name server
* TURN

If you think it's not too long, I can add them.

**Comment by Mikaela** [comment]
Oh, I see, yes, that is too long. What would be the equivalent decentralized list?

**Comment by lrq3000** [comment]
Oh, tough question, I think that's still a topic of research. I think Session (Loki Messenger) implements workarounds for most of these:

* push notifications -> no real way around having a central server if phones aren't rooted, but what Session does for example is that the server is only used to regularly ping the phone and it's the phone which connects to the network to check if there are any new messages, the server has no clue (info from one of their blog post IIRC).
* the OpenDHT proxy -> federated servers (Riot) or onion-like nodes (future Session) or onion-like proxy nodes (current Session)
* bootstrap -> no clue, but I guess fixing the previous may also fix the need for a bootstrap.
* name server -> [Alpenhorn](https://github.com/vuvuzela/alpenhorn) (Vuvuzela bootstrapping and name resolving system). Also probably interesting to look at what some blockchains are doing to associate names with a public key.
* TURN -> no real alternative to my knowledge, or have a list of federated TURN servers, that's all. Or don't use them (it's optional in Jami BTW).

**Pull request merged**
