### PR TITLE
Update RetroShare URL - moved to github 2 years ago

### PR DESCRIPTION
**Pull request by quiddity-wp**
### HTML Preview

*Replace [GITHUB_USERNAME] with your GitHub username and [BRANCH] with the branch name.*

http://htmlpreview.github.io/?https://github.com/quiddity-wp/privacytools.io/blob/master/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
https://github.com/RetroShare/retroshare.github.io

https://retroshare.github.io

http://retroshare.net/

**Comment by Shifterovich** [comment]
@kewde @hugoncosta

**Comment by hugoncosta** [comment]
The MSN coloured windows, damn, that brings out the memories. The sourceforge link already redirects to the .net, the github does that too, so yeah I guess it's good to go?

**Comment by Shifterovich** [comment]
No https, but there's nothing we can do about that.

**Comment by hugoncosta** [comment]
Well, since you don't have to give any specific data, I wouldn't see the point on having https. The website code is open source too.

**Comment by BurungHantu1605** [comment]
Changed URLs to: https://retroshare.cc/

**Pull request merged**
