### PR TITLE
Add wire to the chat apps;

### PR DESCRIPTION
**Pull request by mat1th**
Hello, on #186 Wire was suggested to add to the list. See for the discussion on reddit on https://www.reddit.com/r/privacytoolsIO/comments/5vr10k/adding_wire_as_eubased_encrypted_messenger/ 

I've added to the list. But there are now 4 chat apps. Maybe should I create a table like the VPN section.

### CODE REVIEW

**Comment by mat1th** [comment]
There is also a ` Encrypted Video & Voice Messenger` section should I also add Wire to that section?

**Comment by Shifterovich** [comment]
I would.

**Comment by mat1th** [comment]
Okay, I've resized the image to 120x120. And I've created one button Instead of tree se the screenshot. 
wire

**Comment by mat1th** [comment]
By adding wire to the `Encrypted Video & Voice Messenger` section the last one is strange alined. Should I create a new row (`<div class="row">`) for it to fix it? And Now I've using the Green color. So Wire and Signal are green. Which color should it be? 


wire

**Comment by Shifterovich** [comment]
Set Wire to Linphone's colour, Linphone to Jitsi's colour, and remove Jitsi.

**Comment by mat1th** [comment]
I've removed Jitsi; And changed the colors. See the screenshot for information
wirw

**Comment by mat1th** [comment]
The same kind of problem is at the 'Encrypted Instant Messenger' section. See the screenshot. What should I do? Create a table or delete one? 
wire

**Comment by Shifterovich** [comment]
Seems like the colour update wasn't pushed. https://htmlpreview.github.io/?https://raw.githubusercontent.com/mat1th/privacytools.io/94536a9653b7b300873cbeb39981fa21782fa220/index.html#voip Also please do the same for the "Encrypted Instant Messenger" section.

**Comment by kewde** [comment]
ChatSecure is discontinued, it can be removed I believe.

**Comment by mat1th** [comment]
@kewde I think it isn't It has a blog post [chatsecure.org/blog/chatsecure-v4-released/](https://chatsecure.org/blog/chatsecure-v4-released/) that V4 is released in JANUARY 17, 2017. So I've added to the worth Mentioning section of the chat apps. And I've also done that with jitsi.

**Comment by mat1th** [comment]
@Shifterovich Ohh strange. It's fixed now see https://htmlpreview.github.io/?https://raw.githubusercontent.com/mat1th/privacytools.io/07d7a47aa097b0973c06fcc3664f1612f55914c5/index.html#voip

**Comment by kewde** [comment]
@mat1th that is nice to hear, the Google Play store isn't update tho.

**Comment by mat1th** [comment]
@kewde My bad, only the iOS version is maintained. The android version is forked see [chatsecure.org/blog/chatsecure-android-deprecated/](https://chatsecure.org/blog/chatsecure-android-deprecated/)

**Comment by mat1th** [comment]
I'll see that the issue 'Add Onionshare' #160 is closed. But I haven't added it in this pull request.

**Comment by kewde** [comment]
@mat1th I noticed it when I had already referenced it and set things right instantly.

**Comment by mat1th** [comment]
@Shifterovich You did request to change the size from the image. In the commit #08f1738 I've fixed this. So could this PR be merged? Or should @privacytoolsIO have a look on it?

**Comment by mat1th** [comment]
@privacytoolsIO Could you have a look on it?

**Comment by Shifterovich** [comment]
@kewde @privacytoolsIO Can we merge?

**Comment by mat1th** [comment]
@kewde @privacytoolsIO Now the even open sourced their server. See, https://github.com/wireapp/wire-server. Could we merge?

**Comment by mat1th** [comment]
@kewde :tada: on https://htmlpreview.github.io/?https://raw.githubusercontent.com/mat1th/privacytools.io/64926864d90847f8dda71053a0ab80f8c79a82d9/index.html#voip you can see the full with the latest commit.

**Pull request merged**
