### PR TITLE
Add Hosting Section

### PR DESCRIPTION
**Pull request by asddsaz**
## Description
**Description**: Add Hosting Section
**What companies did you add?** DataCell, Orange Websites, and BAHNHOF.
**I have a suggested change**! Great! Plz make a comment so that it may be reviewed. Edits from maintainers are welcomed.

Resolves: #none

### CODE REVIEW

**Comment by asddsaz** [comment]
@pahakalle If there is any non-related changes, it must've been a fluke. However, I cannot find the code to change it. What line is the code on?

**Comment by pahakalle** [comment]
@asddsaz seems to be the first file(Index)

**Comment by Shifterovich** [comment]
Also Mastodon/GNU social and the some mess with the KDL section.

The PR is very messy, it might be easier to just create a new PR **based on a fresh fork**. Please only one change per PR, so git diff should show only the added hosting section.

**Comment by asddsaz** [comment]
ok

**Pull request closed without merging**
