### PR TITLE
Add MicroG Project to MobileOS Section

### PR DESCRIPTION
**Pull request by sim-s-singh**
### Description

The MicroG project aims to provide a replacement for the proprietary Google Apps and Services found in the Android operating system (such as Google Play Services). This project is useful because it allows functionality in applications that depend on GAPPS. I added MicroG to the Worth Mentioning section of MobileOS's and to the warning about GAPPS. 

### Pictures 
microg-pr

### HTML Preview

http://htmlpreview.github.io/?https://github.com/sim-s-singh/privacytools.io/blob/microg/index.html

### CODE REVIEW

**Comment by Shifterovich** [comment]
@kewde

**Comment by hugoncosta** [comment]
Isn't it supposed to be "FOSS" though? I've never seen floss othen than in the dentist.

**Comment by Shifterovich** [comment]
@hugoncosta The `L` is for `libre`. The purpose of it is to explicitly define `free` as `libre`, not `gratis`.

free/libre open source software

**Comment by sim-s-singh** [comment]
To counter what you said, @kewde, OpenGapps serves as an open source installation method for the google apps, while microG serves as the replacement itself. 
It says so on the OpenGApps [about page](http://opengapps.org/#aboutsection): 

> "The Open GApps Project is an open-source effort to script the automatic generation of up-to-date Google Apps packages."

MicroG, according to their motto on their [home page](https://microg.org/) want to implement GApps in an open source way:

> A free-as-in-freedom re-implementation of Google’s proprietary Android user space apps and libraries.

**Comment by kewde** [comment]
@sim-s-singh
You didn't counter anything I said, you just re-iterated what I said. 
OpenGapps -> used a lot but still loads proprietary google code
MicroG -> nice alternative to the above.

**Comment by kewde** [comment]
@Shifterovich feel free to merge if no objections.

**Comment by sim-s-singh** [comment]
@kewde 
Apologies, I misunderstood what you were trying to say. 
Other than that, I don't think there are any other alternatives to GApps.

**Pull request merged**
