### PR TITLE
Remove Non-Free Search Engines | Against Software Criteria

### PR DESCRIPTION
**Pull request by asddsaz**
**Description**: Remove DuckDuckGo, QWANT, and Startpage
**Why**? The software criteria clearly states "**Open Source** but, DuckDuckGo, QWANT, and Startpage are anything but that. It also states "**there can be exceptions if no software is available that meet the criteria.**, this is for good reasons. Please remove these non-free services.

### CODE REVIEW

**Comment by Shifterovich** [comment]
> there can be exceptions if no software is available that meet the criteria

What usable search engines are open source right now?

**Comment by asddsaz** [comment]
@Shifterovich Look into #700, #701, and #702. They are all to add search engines to "Worth Mentioning". If you wish I could add some as a replacement for these non-free services.

And of course, SearX is still listed.

**Comment by 0ndrey** [comment]
I support. Concerning DDG there is a reasoned article: https://www.stoutner.com/new-default-homepage-and-search-engine/
This does not take into account their close ties with Yandex.

**Comment by Shifterovich** [comment]
Depending on how good the others are, we can replace the currently listed non-free ones. I used startpage for some time (but it was too slow for me so I switched back to Google) and the results were quite good. Definitely better than DDG -- at that time.

**Comment by Shifterovich** [comment]
Related: https://github.com/privacytoolsIO/privacytools.io/issues/84#issuecomment-267864788

**Comment by libBletchley** [comment]
Yacy

**Comment by gjhklfdsa** [comment]
@BurungHantu1605  @Shifterovich For what reasons was this PR rejected/closed?

**Pull request closed without merging**
