### PR TITLE
Update ProtonVPN

### PR DESCRIPTION
**Pull request by JonahAragon**
Correct number of servers according to https://protonvpn.com/secure-vpn

### CODE REVIEW

**Comment by hugoncosta** [comment]
Already at 400, should we just put 400+?

**Comment by JonahAragon** [comment]
Huh, they've been busy lol -- that probably seems fine to me.

**Comment by JonahAragon** [comment]
@Mikaela this was more for ensuring factual accuracy since we already have these services listed, but I would agree that we should probably move forward on #914.

**Comment by tbnv** [comment]
ProtonVNP's paid plans start at $**48**/year, not $96/year. Knowing this may help people in choosing their VPN.

_Sorry to comment in an old thread but I guessed this "Update ProtonVPN" discussion would be good enough._

**Pull request merged**
