### PR TITLE
Onionshare

### PR DESCRIPTION
**Pull request by kewde**
### Description
Add onionshare

### HTML Preview

https://htmlpreview.github.io/?https://github.com/kewde/privacytools.io/blob/onionshare/index.html#filesharing

### CODE REVIEW

**Comment by Shifterovich** [comment]
We should add more tools to the File Sharing section.

**Comment by kewde** [comment]
@Shifterovich for now I'd just start with OnionShare, I haven't seen any alternatives that do what OnionShare does. Maybe on I2P?

**Comment by Shifterovich** [comment]
Personally I'd recommend BitTorrent over I2P.

**Comment by kewde** [comment]
I thought this section is specifically aimed towards file sharing with privacy? The BitTorrent protocol has gotten lots of shit over the years about privacy. The files you share are inherently linked to your IP address through Torrents.

**Comment by kewde** [comment]
#190

**Comment by Shifterovich** [comment]
> over I2P

**Comment by kewde** [comment]
The word 'over' has a dubious meaning in that context
> BitTorrent through I2P

**Comment by tjoiw** [comment]
> We should add more tools to the File Sharing section.

But that can be in another PR? Why not merge this one then move for ways to complete the section. You may find more input after you merge this one since readers of the site will notice and therefore will contribute to this unfinished section.

**Pull request merged**
