### PR TITLE
Privacy Badger & Google Analytics

### PR DESCRIPTION
**Pull request by woctezuma**
### Description

I think it is important that users are aware of a limitation of Privacy Badger and do not imagine that uBlock Origin is not needed when using Privacy Badger.

See: https://github.com/privacytoolsIO/privacytools.io/issues/335

### HTML Preview

http://htmlpreview.github.io/?https://github.com/woctezuma/privacytools.io/blob/privacy-badger/index.html

### CODE REVIEW

**Comment by woctezuma** [comment]
The formatting is a bit off, but I don't know how to fix that.

indentation

**Comment by Shifterovich** [comment]
The text is long, height of those lines is more than the height of the image. Just remove the `<br>`.

**Comment by Shifterovich** [comment]
@kewde

**Comment by Shifterovich** [comment]
@beardog108

**Pull request merged**
