### PR TITLE
ProtonVPN and IVPN clients in F-Droid

### PR DESCRIPTION
**Pull request by dngray**
https://deploy-preview-1902--privacytools-io.netlify.app/providers/vpn/#protonvpn
https://deploy-preview-1902--privacytools-io.netlify.app/providers/vpn/#ivpn

### CODE REVIEW

**Comment by dngray** [comment]
Thankfully Mullvad is looking at doing this too https://github.com/mullvad/mullvadvpn-app/issues/1126 then we can make it a requirement for any new provider!

**Comment by ph00lt0** [comment]
Also Mullvad can be used with the Wireguard app from F-Droid.

**Comment by faern** [comment]
@dngray Mullvad is now available on F-Droid: https://f-droid.org/packages/net.mullvad.mullvadvpn/

**Comment by dngray** [comment]
Thanks @faern, we've updated the site accordingly.

**Pull request merged**
