### PR TITLE
Reddit Warrant Canary

### PR DESCRIPTION
**Pull request by SvenKortekaas**
Reddit removed their Warrant Canary so I added a warning at the bottom of the page by the Reddit link

### CODE REVIEW

**Comment by NafeezJS** [comment]
Maybe we can create a simple form for feedback and suggestions, and avoid using Reddit altogether. The nice thing about using Reddit though is that we get to see everyone's discussion on the suggestion to see if it is even worth looking at given the amount of votes. 

I'd be happy to help with creating a form if this is something of concen.

**Comment by alexbooker** [comment]
@SvenKortekaas, I want to see what the community thinks before I act on this pull request. You can follow the discussion [here](https://www.reddit.com/r/privacytoolsIO/comments/4cvv99/reddit_kills_snooping_warrant_canary/d1lstax).

@NafeezJS, I know this is somewhat ironic, but can you please take this discussion to [Reddit](https://www.reddit.com/r/privacytoolsio)? You'll get more community input there.

**Comment by alexbooker** [comment]
The community seems to want this. Merged.

**Comment by NafeezJS** [comment]
@alexbooker, what does the community seem to want?

**Comment by alexbooker** [comment]
@NafeezJS Sorry, I thought it  was clear from context. The community were in favour of the warning @SvenKortekaas added, so I merged this pull request.

**Pull request merged**
